// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hostthermaldiscovery.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HostDiscoveryConfig struct {
	PollingInterval      string                            `protobuf:"bytes,1,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	TempSensorPath       string                            `protobuf:"bytes,2,opt,name=temp_sensor_path,json=tempSensorPath,proto3" json:"temp_sensor_path,omitempty"`
	FreqSensorUrl        string                            `protobuf:"bytes,3,opt,name=freq_sensor_url,json=freqSensorUrl,proto3" json:"freq_sensor_url,omitempty"`
	ThermalThresholds    map[string]*HostThermalThresholds `protobuf:"bytes,4,rep,name=thermal_thresholds,json=thermalThresholds,proto3" json:"thermal_thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HostDiscoveryConfig) Reset()         { *m = HostDiscoveryConfig{} }
func (m *HostDiscoveryConfig) String() string { return proto.CompactTextString(m) }
func (*HostDiscoveryConfig) ProtoMessage()    {}
func (*HostDiscoveryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostthermaldiscovery_0abdfca256266e1f, []int{0}
}
func (m *HostDiscoveryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostDiscoveryConfig.Unmarshal(m, b)
}
func (m *HostDiscoveryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostDiscoveryConfig.Marshal(b, m, deterministic)
}
func (dst *HostDiscoveryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostDiscoveryConfig.Merge(dst, src)
}
func (m *HostDiscoveryConfig) XXX_Size() int {
	return xxx_messageInfo_HostDiscoveryConfig.Size(m)
}
func (m *HostDiscoveryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HostDiscoveryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HostDiscoveryConfig proto.InternalMessageInfo

func (m *HostDiscoveryConfig) GetPollingInterval() string {
	if m != nil {
		return m.PollingInterval
	}
	return ""
}

func (m *HostDiscoveryConfig) GetTempSensorPath() string {
	if m != nil {
		return m.TempSensorPath
	}
	return ""
}

func (m *HostDiscoveryConfig) GetFreqSensorUrl() string {
	if m != nil {
		return m.FreqSensorUrl
	}
	return ""
}

func (m *HostDiscoveryConfig) GetThermalThresholds() map[string]*HostThermalThresholds {
	if m != nil {
		return m.ThermalThresholds
	}
	return nil
}

type HostThermalThresholds struct {
	LowerNormal          int32    `protobuf:"varint,1,opt,name=lower_normal,json=lowerNormal,proto3" json:"lower_normal,omitempty"`
	UpperNormal          int32    `protobuf:"varint,2,opt,name=upper_normal,json=upperNormal,proto3" json:"upper_normal,omitempty"`
	LowerHigh            int32    `protobuf:"varint,3,opt,name=lower_high,json=lowerHigh,proto3" json:"lower_high,omitempty"`
	UpperHigh            int32    `protobuf:"varint,4,opt,name=upper_high,json=upperHigh,proto3" json:"upper_high,omitempty"`
	LowerCritical        int32    `protobuf:"varint,5,opt,name=lower_critical,json=lowerCritical,proto3" json:"lower_critical,omitempty"`
	UpperCritical        int32    `protobuf:"varint,6,opt,name=upper_critical,json=upperCritical,proto3" json:"upper_critical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostThermalThresholds) Reset()         { *m = HostThermalThresholds{} }
func (m *HostThermalThresholds) String() string { return proto.CompactTextString(m) }
func (*HostThermalThresholds) ProtoMessage()    {}
func (*HostThermalThresholds) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostthermaldiscovery_0abdfca256266e1f, []int{1}
}
func (m *HostThermalThresholds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostThermalThresholds.Unmarshal(m, b)
}
func (m *HostThermalThresholds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostThermalThresholds.Marshal(b, m, deterministic)
}
func (dst *HostThermalThresholds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostThermalThresholds.Merge(dst, src)
}
func (m *HostThermalThresholds) XXX_Size() int {
	return xxx_messageInfo_HostThermalThresholds.Size(m)
}
func (m *HostThermalThresholds) XXX_DiscardUnknown() {
	xxx_messageInfo_HostThermalThresholds.DiscardUnknown(m)
}

var xxx_messageInfo_HostThermalThresholds proto.InternalMessageInfo

func (m *HostThermalThresholds) GetLowerNormal() int32 {
	if m != nil {
		return m.LowerNormal
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperNormal() int32 {
	if m != nil {
		return m.UpperNormal
	}
	return 0
}

func (m *HostThermalThresholds) GetLowerHigh() int32 {
	if m != nil {
		return m.LowerHigh
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperHigh() int32 {
	if m != nil {
		return m.UpperHigh
	}
	return 0
}

func (m *HostThermalThresholds) GetLowerCritical() int32 {
	if m != nil {
		return m.LowerCritical
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperCritical() int32 {
	if m != nil {
		return m.UpperCritical
	}
	return 0
}

func init() {
	proto.RegisterType((*HostDiscoveryConfig)(nil), "proto.HostDiscoveryConfig")
	proto.RegisterMapType((map[string]*HostThermalThresholds)(nil), "proto.HostDiscoveryConfig.ThermalThresholdsEntry")
	proto.RegisterType((*HostThermalThresholds)(nil), "proto.HostThermalThresholds")
}

func init() {
	proto.RegisterFile("hostthermaldiscovery.proto", fileDescriptor_hostthermaldiscovery_0abdfca256266e1f)
}

var fileDescriptor_hostthermaldiscovery_0abdfca256266e1f = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x5f, 0x4f, 0xf2, 0x30,
	0x14, 0xc6, 0xb3, 0xc1, 0x48, 0x38, 0xbc, 0xfc, 0x79, 0x6b, 0x34, 0x0b, 0xd1, 0x04, 0x49, 0x34,
	0x78, 0x43, 0x22, 0xde, 0x18, 0x6f, 0xd1, 0x04, 0x6f, 0x8c, 0x99, 0x78, 0x3d, 0x07, 0x94, 0xb5,
	0xb1, 0xac, 0xb3, 0x2d, 0x18, 0xbe, 0xa9, 0x5f, 0xc1, 0x6f, 0x61, 0x7a, 0x3a, 0xd0, 0xe8, 0xae,
	0xb6, 0xfc, 0x9e, 0xdf, 0x39, 0x7d, 0x5a, 0xe8, 0x32, 0xa9, 0x8d, 0x61, 0x54, 0xad, 0x12, 0xb1,
	0xe0, 0x7a, 0x2e, 0x37, 0x54, 0x6d, 0x87, 0xb9, 0x92, 0x46, 0x92, 0x00, 0x3f, 0xfd, 0x0f, 0x1f,
	0x0e, 0x26, 0x52, 0x9b, 0xdb, 0x5d, 0x3c, 0x96, 0xd9, 0x92, 0xa7, 0xe4, 0x02, 0x3a, 0xb9, 0x14,
	0x82, 0x67, 0x69, 0xcc, 0x33, 0x43, 0xd5, 0x26, 0x11, 0xa1, 0xd7, 0xf3, 0x06, 0xf5, 0xa8, 0x5d,
	0xf0, 0xfb, 0x02, 0x93, 0x01, 0x74, 0x0c, 0x5d, 0xe5, 0xb1, 0xa6, 0x99, 0x96, 0x2a, 0xce, 0x13,
	0xc3, 0x42, 0x1f, 0xd5, 0x96, 0xe5, 0x4f, 0x88, 0x1f, 0x13, 0xc3, 0xc8, 0x39, 0xb4, 0x97, 0x8a,
	0xbe, 0xed, 0xcc, 0xb5, 0x12, 0x61, 0x05, 0xc5, 0xa6, 0xc5, 0x4e, 0x7c, 0x56, 0x82, 0xbc, 0x00,
	0x29, 0x5a, 0xc7, 0x86, 0x29, 0xaa, 0x99, 0x14, 0x0b, 0x1d, 0x56, 0x7b, 0x95, 0x41, 0x63, 0x74,
	0xe9, 0xfa, 0x0f, 0x4b, 0x4a, 0x0f, 0xa7, 0x6e, 0x68, 0xba, 0x9f, 0xb9, 0xcb, 0x8c, 0xda, 0x46,
	0xff, 0xcd, 0x6f, 0xde, 0x9d, 0xc1, 0x51, 0xb9, 0x4c, 0x3a, 0x50, 0x79, 0xa5, 0xdb, 0xe2, 0xae,
	0xf6, 0x97, 0x8c, 0x20, 0xd8, 0x24, 0x62, 0x4d, 0xf1, 0x52, 0x8d, 0xd1, 0xf1, 0x8f, 0x02, 0x7f,
	0x76, 0x44, 0x4e, 0xbd, 0xf1, 0xaf, 0xbd, 0xfe, 0xa7, 0x07, 0x87, 0xa5, 0x12, 0x39, 0x85, 0x7f,
	0x42, 0xbe, 0x53, 0x15, 0x67, 0xd2, 0x26, 0x78, 0x58, 0x10, 0x35, 0x90, 0x3d, 0x20, 0xb2, 0xca,
	0x3a, 0xcf, 0xbf, 0x15, 0xdf, 0x29, 0xc8, 0x0a, 0xe5, 0x04, 0xc0, 0x6d, 0x61, 0x3c, 0x65, 0xf8,
	0x90, 0x41, 0x54, 0x47, 0x32, 0xe1, 0x29, 0xb3, 0xb1, 0xdb, 0x80, 0x71, 0xd5, 0xc5, 0x48, 0x30,
	0x3e, 0x83, 0x96, 0x9b, 0x9e, 0x2b, 0x6e, 0xf8, 0x3c, 0x11, 0x61, 0x80, 0x4a, 0x13, 0xe9, 0xb8,
	0x80, 0x56, 0x73, 0x5b, 0xf6, 0x5a, 0xcd, 0x69, 0x48, 0x77, 0xda, 0xac, 0x86, 0x6f, 0x72, 0xf5,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x54, 0x75, 0x3e, 0x54, 0x72, 0x02, 0x00, 0x00,
}
