// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hostthermaldiscovery.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HostDiscoveryConfig struct {
	PollingInterval      string                            `protobuf:"bytes,1,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	TempSensorPath       string                            `protobuf:"bytes,2,opt,name=temp_sensor_path,json=tempSensorPath,proto3" json:"temp_sensor_path,omitempty"`
	FreqSensorUrl        string                            `protobuf:"bytes,3,opt,name=freq_sensor_url,json=freqSensorUrl,proto3" json:"freq_sensor_url,omitempty"`
	ThermalThresholds    map[string]*HostThermalThresholds `protobuf:"bytes,4,rep,name=thermal_thresholds,json=thermalThresholds,proto3" json:"thermal_thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LogThermalData       bool                              `protobuf:"varint,5,opt,name=log_thermal_data,json=logThermalData,proto3" json:"log_thermal_data,omitempty"`
	LogHere              string                            `protobuf:"bytes,6,opt,name=log_here,json=logHere,proto3" json:"log_here,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HostDiscoveryConfig) Reset()         { *m = HostDiscoveryConfig{} }
func (m *HostDiscoveryConfig) String() string { return proto.CompactTextString(m) }
func (*HostDiscoveryConfig) ProtoMessage()    {}
func (*HostDiscoveryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostthermaldiscovery_bfeffec62fafe688, []int{0}
}
func (m *HostDiscoveryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostDiscoveryConfig.Unmarshal(m, b)
}
func (m *HostDiscoveryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostDiscoveryConfig.Marshal(b, m, deterministic)
}
func (dst *HostDiscoveryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostDiscoveryConfig.Merge(dst, src)
}
func (m *HostDiscoveryConfig) XXX_Size() int {
	return xxx_messageInfo_HostDiscoveryConfig.Size(m)
}
func (m *HostDiscoveryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HostDiscoveryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HostDiscoveryConfig proto.InternalMessageInfo

func (m *HostDiscoveryConfig) GetPollingInterval() string {
	if m != nil {
		return m.PollingInterval
	}
	return ""
}

func (m *HostDiscoveryConfig) GetTempSensorPath() string {
	if m != nil {
		return m.TempSensorPath
	}
	return ""
}

func (m *HostDiscoveryConfig) GetFreqSensorUrl() string {
	if m != nil {
		return m.FreqSensorUrl
	}
	return ""
}

func (m *HostDiscoveryConfig) GetThermalThresholds() map[string]*HostThermalThresholds {
	if m != nil {
		return m.ThermalThresholds
	}
	return nil
}

func (m *HostDiscoveryConfig) GetLogThermalData() bool {
	if m != nil {
		return m.LogThermalData
	}
	return false
}

func (m *HostDiscoveryConfig) GetLogHere() string {
	if m != nil {
		return m.LogHere
	}
	return ""
}

type HostThermalThresholds struct {
	LowerNormal          int32    `protobuf:"varint,1,opt,name=lower_normal,json=lowerNormal,proto3" json:"lower_normal,omitempty"`
	UpperNormal          int32    `protobuf:"varint,2,opt,name=upper_normal,json=upperNormal,proto3" json:"upper_normal,omitempty"`
	LowerHigh            int32    `protobuf:"varint,3,opt,name=lower_high,json=lowerHigh,proto3" json:"lower_high,omitempty"`
	UpperHigh            int32    `protobuf:"varint,4,opt,name=upper_high,json=upperHigh,proto3" json:"upper_high,omitempty"`
	LowerCritical        int32    `protobuf:"varint,5,opt,name=lower_critical,json=lowerCritical,proto3" json:"lower_critical,omitempty"`
	UpperCritical        int32    `protobuf:"varint,6,opt,name=upper_critical,json=upperCritical,proto3" json:"upper_critical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostThermalThresholds) Reset()         { *m = HostThermalThresholds{} }
func (m *HostThermalThresholds) String() string { return proto.CompactTextString(m) }
func (*HostThermalThresholds) ProtoMessage()    {}
func (*HostThermalThresholds) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostthermaldiscovery_bfeffec62fafe688, []int{1}
}
func (m *HostThermalThresholds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostThermalThresholds.Unmarshal(m, b)
}
func (m *HostThermalThresholds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostThermalThresholds.Marshal(b, m, deterministic)
}
func (dst *HostThermalThresholds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostThermalThresholds.Merge(dst, src)
}
func (m *HostThermalThresholds) XXX_Size() int {
	return xxx_messageInfo_HostThermalThresholds.Size(m)
}
func (m *HostThermalThresholds) XXX_DiscardUnknown() {
	xxx_messageInfo_HostThermalThresholds.DiscardUnknown(m)
}

var xxx_messageInfo_HostThermalThresholds proto.InternalMessageInfo

func (m *HostThermalThresholds) GetLowerNormal() int32 {
	if m != nil {
		return m.LowerNormal
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperNormal() int32 {
	if m != nil {
		return m.UpperNormal
	}
	return 0
}

func (m *HostThermalThresholds) GetLowerHigh() int32 {
	if m != nil {
		return m.LowerHigh
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperHigh() int32 {
	if m != nil {
		return m.UpperHigh
	}
	return 0
}

func (m *HostThermalThresholds) GetLowerCritical() int32 {
	if m != nil {
		return m.LowerCritical
	}
	return 0
}

func (m *HostThermalThresholds) GetUpperCritical() int32 {
	if m != nil {
		return m.UpperCritical
	}
	return 0
}

func init() {
	proto.RegisterType((*HostDiscoveryConfig)(nil), "proto.HostDiscoveryConfig")
	proto.RegisterMapType((map[string]*HostThermalThresholds)(nil), "proto.HostDiscoveryConfig.ThermalThresholdsEntry")
	proto.RegisterType((*HostThermalThresholds)(nil), "proto.HostThermalThresholds")
}

func init() {
	proto.RegisterFile("hostthermaldiscovery.proto", fileDescriptor_hostthermaldiscovery_bfeffec62fafe688)
}

var fileDescriptor_hostthermaldiscovery_bfeffec62fafe688 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4f, 0xc2, 0x30,
	0x18, 0xc7, 0x33, 0xc6, 0x10, 0x8a, 0xbc, 0x58, 0xa3, 0x99, 0x44, 0x13, 0x24, 0xd1, 0xcc, 0x0b,
	0x89, 0x78, 0x31, 0x5e, 0xc1, 0x04, 0x2f, 0xc6, 0x4c, 0x3c, 0xcf, 0x02, 0x65, 0x6d, 0x2c, 0xeb,
	0xec, 0x0a, 0x86, 0x0f, 0xe3, 0x07, 0xf4, 0x5b, 0x98, 0x3e, 0xdd, 0xd0, 0x28, 0xa7, 0x2d, 0xbf,
	0xff, 0xef, 0x79, 0xd9, 0x33, 0xd4, 0x61, 0x32, 0xd3, 0x9a, 0x51, 0xb5, 0x24, 0x62, 0xce, 0xb3,
	0x99, 0x5c, 0x53, 0xb5, 0xe9, 0xa7, 0x4a, 0x6a, 0x89, 0x3d, 0x78, 0xf4, 0x3e, 0x5d, 0x74, 0x38,
	0x96, 0x99, 0x1e, 0x15, 0xf1, 0x50, 0x26, 0x0b, 0x1e, 0xe3, 0x2b, 0xd4, 0x4e, 0xa5, 0x10, 0x3c,
	0x89, 0x23, 0x9e, 0x68, 0xaa, 0xd6, 0x44, 0xf8, 0x4e, 0xd7, 0x09, 0x6a, 0x61, 0x2b, 0xe7, 0x0f,
	0x39, 0xc6, 0x01, 0x6a, 0x6b, 0xba, 0x4c, 0xa3, 0x8c, 0x26, 0x99, 0x54, 0x51, 0x4a, 0x34, 0xf3,
	0x4b, 0xa0, 0x36, 0x0d, 0x7f, 0x06, 0xfc, 0x44, 0x34, 0xc3, 0x97, 0xa8, 0xb5, 0x50, 0xf4, 0xbd,
	0x30, 0x57, 0x4a, 0xf8, 0x2e, 0x88, 0x0d, 0x83, 0xad, 0xf8, 0xa2, 0x04, 0x7e, 0x45, 0x38, 0xdf,
	0x3a, 0xd2, 0x4c, 0xd1, 0x8c, 0x49, 0x31, 0xcf, 0xfc, 0x72, 0xd7, 0x0d, 0xea, 0x83, 0x6b, 0xbb,
	0x7f, 0x7f, 0xc7, 0xd2, 0xfd, 0x89, 0x2d, 0x9a, 0x6c, 0x6b, 0xee, 0x13, 0xad, 0x36, 0xe1, 0x81,
	0xfe, 0xcb, 0xcd, 0xce, 0x42, 0xc6, 0x51, 0x31, 0x65, 0x4e, 0x34, 0xf1, 0xbd, 0xae, 0x13, 0x54,
	0xc3, 0xa6, 0x90, 0x71, 0xde, 0x67, 0x44, 0x34, 0xc1, 0x27, 0xa8, 0x6a, 0x4c, 0x46, 0x15, 0xf5,
	0x2b, 0xb0, 0xec, 0x9e, 0x90, 0xf1, 0x98, 0x2a, 0xda, 0x99, 0xa2, 0xe3, 0xdd, 0x13, 0x71, 0x1b,
	0xb9, 0x6f, 0x74, 0x93, 0x1f, 0xcc, 0xbc, 0xe2, 0x01, 0xf2, 0xd6, 0x44, 0xac, 0x28, 0x5c, 0xa6,
	0x3e, 0x38, 0xfd, 0xf5, 0x15, 0xff, 0x7a, 0x84, 0x56, 0xbd, 0x2b, 0xdd, 0x3a, 0xbd, 0x2f, 0x07,
	0x1d, 0xed, 0x94, 0xf0, 0x39, 0xda, 0x17, 0xf2, 0x83, 0xaa, 0x28, 0x91, 0x26, 0x81, 0x61, 0x5e,
	0x58, 0x07, 0xf6, 0x08, 0xc8, 0x28, 0xab, 0x34, 0xfd, 0x51, 0x4a, 0x56, 0x01, 0x96, 0x2b, 0x67,
	0x08, 0xd9, 0x2e, 0x8c, 0xc7, 0x0c, 0xfe, 0x86, 0x17, 0xd6, 0x80, 0x8c, 0x79, 0xcc, 0x4c, 0x6c,
	0x3b, 0x40, 0x5c, 0xb6, 0x31, 0x10, 0x88, 0x2f, 0x50, 0xd3, 0x56, 0xcf, 0x14, 0xd7, 0x7c, 0x46,
	0x04, 0x1c, 0xd1, 0x0b, 0x1b, 0x40, 0x87, 0x39, 0x34, 0x9a, 0xed, 0xb2, 0xd5, 0x2a, 0x56, 0x03,
	0x5a, 0x68, 0xd3, 0x0a, 0xdc, 0xe4, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x86, 0x77, 0xab, 0x62,
	0xb7, 0x02, 0x00, 0x00,
}
