// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipxe.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PiPXEConfig struct {
	SrvIfaceUrl          string   `protobuf:"bytes,1,opt,name=srv_iface_url,json=srvIfaceUrl,proto3" json:"srv_iface_url,omitempty"`
	SrvIpUrl             string   `protobuf:"bytes,2,opt,name=srv_ip_url,json=srvIpUrl,proto3" json:"srv_ip_url,omitempty"`
	IpUrl                string   `protobuf:"bytes,3,opt,name=ip_url,json=ipUrl,proto3" json:"ip_url,omitempty"`
	NmUrl                string   `protobuf:"bytes,4,opt,name=nm_url,json=nmUrl,proto3" json:"nm_url,omitempty"`
	MacUrl               string   `protobuf:"bytes,5,opt,name=mac_url,json=macUrl,proto3" json:"mac_url,omitempty"`
	SubnetUrl            string   `protobuf:"bytes,6,opt,name=subnet_url,json=subnetUrl,proto3" json:"subnet_url,omitempty"`
	TftpDir              string   `protobuf:"bytes,7,opt,name=tftp_dir,json=tftpDir,proto3" json:"tftp_dir,omitempty"`
	ArpDeadline          string   `protobuf:"bytes,8,opt,name=arp_deadline,json=arpDeadline,proto3" json:"arp_deadline,omitempty"`
	DhcpRetry            uint32   `protobuf:"varint,9,opt,name=dhcp_retry,json=dhcpRetry,proto3" json:"dhcp_retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiPXEConfig) Reset()         { *m = PiPXEConfig{} }
func (m *PiPXEConfig) String() string { return proto.CompactTextString(m) }
func (*PiPXEConfig) ProtoMessage()    {}
func (*PiPXEConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pipxe_2d90fd0892480f40, []int{0}
}
func (m *PiPXEConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiPXEConfig.Unmarshal(m, b)
}
func (m *PiPXEConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiPXEConfig.Marshal(b, m, deterministic)
}
func (dst *PiPXEConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiPXEConfig.Merge(dst, src)
}
func (m *PiPXEConfig) XXX_Size() int {
	return xxx_messageInfo_PiPXEConfig.Size(m)
}
func (m *PiPXEConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PiPXEConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PiPXEConfig proto.InternalMessageInfo

func (m *PiPXEConfig) GetSrvIfaceUrl() string {
	if m != nil {
		return m.SrvIfaceUrl
	}
	return ""
}

func (m *PiPXEConfig) GetSrvIpUrl() string {
	if m != nil {
		return m.SrvIpUrl
	}
	return ""
}

func (m *PiPXEConfig) GetIpUrl() string {
	if m != nil {
		return m.IpUrl
	}
	return ""
}

func (m *PiPXEConfig) GetNmUrl() string {
	if m != nil {
		return m.NmUrl
	}
	return ""
}

func (m *PiPXEConfig) GetMacUrl() string {
	if m != nil {
		return m.MacUrl
	}
	return ""
}

func (m *PiPXEConfig) GetSubnetUrl() string {
	if m != nil {
		return m.SubnetUrl
	}
	return ""
}

func (m *PiPXEConfig) GetTftpDir() string {
	if m != nil {
		return m.TftpDir
	}
	return ""
}

func (m *PiPXEConfig) GetArpDeadline() string {
	if m != nil {
		return m.ArpDeadline
	}
	return ""
}

func (m *PiPXEConfig) GetDhcpRetry() uint32 {
	if m != nil {
		return m.DhcpRetry
	}
	return 0
}

func init() {
	proto.RegisterType((*PiPXEConfig)(nil), "proto.PiPXEConfig")
}

func init() { proto.RegisterFile("pipxe.proto", fileDescriptor_pipxe_2d90fd0892480f40) }

var fileDescriptor_pipxe_2d90fd0892480f40 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xd0, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x71, 0x52, 0xcd, 0xbf, 0x89, 0xbd, 0x04, 0xc4, 0x08, 0x0a, 0xb5, 0xa7, 0x9e, 0xbc,
	0xf8, 0x08, 0xd6, 0x83, 0xb7, 0x12, 0x10, 0xbc, 0x2d, 0xdb, 0x64, 0xa3, 0x03, 0xc9, 0x66, 0x98,
	0x6c, 0x8b, 0xbe, 0x86, 0x4f, 0x2c, 0x33, 0x49, 0x4f, 0x21, 0x9f, 0xef, 0x8f, 0x85, 0x5d, 0x28,
	0x08, 0xe9, 0xc7, 0x3d, 0x13, 0x8f, 0x61, 0x2c, 0x63, 0xfd, 0x6c, 0xff, 0x56, 0x50, 0x1c, 0xf0,
	0xf0, 0xf9, 0xf6, 0x3a, 0xfa, 0x0e, 0xbf, 0xca, 0x2d, 0xac, 0x27, 0x3e, 0x1b, 0xec, 0x6c, 0xe3,
	0xcc, 0x89, 0xfb, 0x2a, 0xda, 0x44, 0xbb, 0xbc, 0x2e, 0x26, 0x3e, 0xbf, 0x8b, 0x7d, 0x70, 0x5f,
	0x3e, 0x00, 0xe8, 0x86, 0x74, 0xb0, 0xd2, 0x41, 0x26, 0x03, 0x92, 0x7a, 0x0b, 0xc9, 0x52, 0xae,
	0xb4, 0xc4, 0x78, 0x61, 0x3f, 0x28, 0x5f, 0xcf, 0xec, 0x07, 0xe1, 0x3b, 0x48, 0x07, 0xdb, 0xa8,
	0xc7, 0xea, 0xc9, 0x60, 0x1b, 0x09, 0x8f, 0x00, 0xd3, 0xe9, 0xe8, 0x5d, 0xd0, 0x96, 0x68, 0xcb,
	0x67, 0x91, 0x7c, 0x0f, 0x59, 0xe8, 0x02, 0x99, 0x16, 0xb9, 0x4a, 0x35, 0xa6, 0xf2, 0xbf, 0x47,
	0x2e, 0x9f, 0xe0, 0xc6, 0x32, 0x99, 0xd6, 0xd9, 0xb6, 0x47, 0xef, 0xaa, 0x6c, 0xbe, 0x81, 0x65,
	0xda, 0x2f, 0x24, 0x87, 0xb7, 0xdf, 0x0d, 0x19, 0x76, 0x81, 0x7f, 0xab, 0x7c, 0x13, 0xed, 0xd6,
	0x75, 0x2e, 0x52, 0x0b, 0x1c, 0x13, 0x7d, 0x9b, 0x97, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5,
	0x3c, 0xb5, 0x31, 0x31, 0x01, 0x00, 0x00,
}
