---
- hosts: kraken
  vars:
    kr_repo: https://github.com/synackd/kraken.git
    kr_repo_version: "uroot-as-target"
    kr_build_args: "-v -force"
  roles:
    - common
    - kraken-all
    - kraken-dashboard
#    - extras
