---
- hosts: kraken
  vars:
    kr_repo: https://github.com/kpelzel0522/kraken.git
    kr_repo_version: "bug/graph-color"
    kr_build_args: "-v -force"
  roles:
    - common
    - kraken-all
    - kraken-dashboard
#    - extras
