---
- name: Install kraken service file
  become: true
  template:
    src: 'kraken.service.j2'
    dest: '/usr/lib/systemd/system/kraken.service'
    owner: root
    group: root
    mode: 0644
  when: not kr_rpm

- name: Install kraken environment file
  become: true
  template:
    src: 'kraken.environment.j2'
    dest: '/etc/sysconfig/kraken'
    owner: root
    group: root
    mode: 0644

- name: Enable & start kraken service
  become: true
  systemd:
    name: kraken.service
    enabled: true
    state: started
    daemon_reload: true