// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ModuleAPI.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ServiceControl_Command int32

const (
	ServiceControl_STOP   ServiceControl_Command = 0
	ServiceControl_UPDATE ServiceControl_Command = 1
	ServiceControl_INIT   ServiceControl_Command = 2
)

var ServiceControl_Command_name = map[int32]string{
	0: "STOP",
	1: "UPDATE",
	2: "INIT",
}

var ServiceControl_Command_value = map[string]int32{
	"STOP":   0,
	"UPDATE": 1,
	"INIT":   2,
}

func (x ServiceControl_Command) String() string {
	return proto.EnumName(ServiceControl_Command_name, int32(x))
}

func (ServiceControl_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{3, 0}
}

type MutationControl_Type int32

const (
	MutationControl_MUTATE    MutationControl_Type = 0
	MutationControl_INTERRUPT MutationControl_Type = 1
)

var MutationControl_Type_name = map[int32]string{
	0: "MUTATE",
	1: "INTERRUPT",
}

var MutationControl_Type_value = map[string]int32{
	"MUTATE":    0,
	"INTERRUPT": 1,
}

func (x MutationControl_Type) String() string {
	return proto.EnumName(MutationControl_Type_name, int32(x))
}

func (MutationControl_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{4, 0}
}

type StateChangeControl_Type int32

const (
	StateChangeControl_CREATE     StateChangeControl_Type = 0
	StateChangeControl_READ       StateChangeControl_Type = 1
	StateChangeControl_UPDATE     StateChangeControl_Type = 2
	StateChangeControl_DELETE     StateChangeControl_Type = 3
	StateChangeControl_CFG_READ   StateChangeControl_Type = 4
	StateChangeControl_CFG_UPDATE StateChangeControl_Type = 5
)

var StateChangeControl_Type_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE",
	3: "DELETE",
	4: "CFG_READ",
	5: "CFG_UPDATE",
}

var StateChangeControl_Type_value = map[string]int32{
	"CREATE":     0,
	"READ":       1,
	"UPDATE":     2,
	"DELETE":     3,
	"CFG_READ":   4,
	"CFG_UPDATE": 5,
}

func (x StateChangeControl_Type) String() string {
	return proto.EnumName(StateChangeControl_Type_name, int32(x))
}

func (StateChangeControl_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{5, 0}
}

type EventControl_Type int32

const (
	EventControl_StateChange EventControl_Type = 0
	EventControl_Mutation    EventControl_Type = 1
	EventControl_Discovery   EventControl_Type = 2
)

var EventControl_Type_name = map[int32]string{
	0: "StateChange",
	1: "Mutation",
	2: "Discovery",
}

var EventControl_Type_value = map[string]int32{
	"StateChange": 0,
	"Mutation":    1,
	"Discovery":   2,
}

func (x EventControl_Type) String() string {
	return proto.EnumName(EventControl_Type_name, int32(x))
}

func (EventControl_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{6, 0}
}

type Query struct {
	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Query_Node
	//	*Query_Text
	//	*Query_Bool
	//	*Query_MutationNodeList
	//	*Query_MutationEdgeList
	//	*Query_MutationPath
	Payload              isQuery_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{0}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

type isQuery_Payload interface {
	isQuery_Payload()
}

type Query_Node struct {
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3,oneof" json:"node,omitempty"`
}
type Query_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
}
type Query_Bool struct {
	Bool bool `protobuf:"varint,4,opt,name=bool,proto3,oneof" json:"bool,omitempty"`
}
type Query_MutationNodeList struct {
	MutationNodeList *MutationNodeList `protobuf:"bytes,5,opt,name=mutationNodeList,proto3,oneof" json:"mutationNodeList,omitempty"`
}
type Query_MutationEdgeList struct {
	MutationEdgeList *MutationEdgeList `protobuf:"bytes,6,opt,name=mutationEdgeList,proto3,oneof" json:"mutationEdgeList,omitempty"`
}
type Query_MutationPath struct {
	MutationPath *MutationPath `protobuf:"bytes,7,opt,name=mutationPath,proto3,oneof" json:"mutationPath,omitempty"`
}

func (*Query_Node) isQuery_Payload()             {}
func (*Query_Text) isQuery_Payload()             {}
func (*Query_Bool) isQuery_Payload()             {}
func (*Query_MutationNodeList) isQuery_Payload() {}
func (*Query_MutationEdgeList) isQuery_Payload() {}
func (*Query_MutationPath) isQuery_Payload()     {}

func (m *Query) GetPayload() isQuery_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Query) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Query) GetNode() *Node {
	if x, ok := m.GetPayload().(*Query_Node); ok {
		return x.Node
	}
	return nil
}

func (m *Query) GetText() string {
	if x, ok := m.GetPayload().(*Query_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Query) GetBool() bool {
	if x, ok := m.GetPayload().(*Query_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Query) GetMutationNodeList() *MutationNodeList {
	if x, ok := m.GetPayload().(*Query_MutationNodeList); ok {
		return x.MutationNodeList
	}
	return nil
}

func (m *Query) GetMutationEdgeList() *MutationEdgeList {
	if x, ok := m.GetPayload().(*Query_MutationEdgeList); ok {
		return x.MutationEdgeList
	}
	return nil
}

func (m *Query) GetMutationPath() *MutationPath {
	if x, ok := m.GetPayload().(*Query_MutationPath); ok {
		return x.MutationPath
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Query) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Query_Node)(nil),
		(*Query_Text)(nil),
		(*Query_Bool)(nil),
		(*Query_MutationNodeList)(nil),
		(*Query_MutationEdgeList)(nil),
		(*Query_MutationPath)(nil),
	}
}

type QueryMulti struct {
	Queries              []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMulti) Reset()         { *m = QueryMulti{} }
func (m *QueryMulti) String() string { return proto.CompactTextString(m) }
func (*QueryMulti) ProtoMessage()    {}
func (*QueryMulti) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{1}
}
func (m *QueryMulti) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMulti.Unmarshal(m, b)
}
func (m *QueryMulti) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMulti.Marshal(b, m, deterministic)
}
func (m *QueryMulti) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMulti.Merge(m, src)
}
func (m *QueryMulti) XXX_Size() int {
	return xxx_messageInfo_QueryMulti.Size(m)
}
func (m *QueryMulti) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMulti.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMulti proto.InternalMessageInfo

func (m *QueryMulti) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type ServiceInitRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Module               string   `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInitRequest) Reset()         { *m = ServiceInitRequest{} }
func (m *ServiceInitRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceInitRequest) ProtoMessage()    {}
func (*ServiceInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{2}
}
func (m *ServiceInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInitRequest.Unmarshal(m, b)
}
func (m *ServiceInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInitRequest.Marshal(b, m, deterministic)
}
func (m *ServiceInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInitRequest.Merge(m, src)
}
func (m *ServiceInitRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceInitRequest.Size(m)
}
func (m *ServiceInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInitRequest proto.InternalMessageInfo

func (m *ServiceInitRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceInitRequest) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type ServiceControl struct {
	Command              ServiceControl_Command `protobuf:"varint,1,opt,name=command,proto3,enum=proto.ServiceControl_Command" json:"command,omitempty"`
	Config               *any.Any               `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServiceControl) Reset()         { *m = ServiceControl{} }
func (m *ServiceControl) String() string { return proto.CompactTextString(m) }
func (*ServiceControl) ProtoMessage()    {}
func (*ServiceControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{3}
}
func (m *ServiceControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceControl.Unmarshal(m, b)
}
func (m *ServiceControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceControl.Marshal(b, m, deterministic)
}
func (m *ServiceControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceControl.Merge(m, src)
}
func (m *ServiceControl) XXX_Size() int {
	return xxx_messageInfo_ServiceControl.Size(m)
}
func (m *ServiceControl) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceControl.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceControl proto.InternalMessageInfo

func (m *ServiceControl) GetCommand() ServiceControl_Command {
	if m != nil {
		return m.Command
	}
	return ServiceControl_STOP
}

func (m *ServiceControl) GetConfig() *any.Any {
	if m != nil {
		return m.Config
	}
	return nil
}

type MutationControl struct {
	Module               string               `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 MutationControl_Type `protobuf:"varint,3,opt,name=type,proto3,enum=proto.MutationControl_Type" json:"type,omitempty"`
	Cfg                  *Node                `protobuf:"bytes,4,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Dsc                  *Node                `protobuf:"bytes,5,opt,name=dsc,proto3" json:"dsc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MutationControl) Reset()         { *m = MutationControl{} }
func (m *MutationControl) String() string { return proto.CompactTextString(m) }
func (*MutationControl) ProtoMessage()    {}
func (*MutationControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{4}
}
func (m *MutationControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationControl.Unmarshal(m, b)
}
func (m *MutationControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationControl.Marshal(b, m, deterministic)
}
func (m *MutationControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationControl.Merge(m, src)
}
func (m *MutationControl) XXX_Size() int {
	return xxx_messageInfo_MutationControl.Size(m)
}
func (m *MutationControl) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationControl.DiscardUnknown(m)
}

var xxx_messageInfo_MutationControl proto.InternalMessageInfo

func (m *MutationControl) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MutationControl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MutationControl) GetType() MutationControl_Type {
	if m != nil {
		return m.Type
	}
	return MutationControl_MUTATE
}

func (m *MutationControl) GetCfg() *Node {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *MutationControl) GetDsc() *Node {
	if m != nil {
		return m.Dsc
	}
	return nil
}

type StateChangeControl struct {
	Type                 StateChangeControl_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.StateChangeControl_Type" json:"type,omitempty"`
	Url                  string                  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Value                string                  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateChangeControl) Reset()         { *m = StateChangeControl{} }
func (m *StateChangeControl) String() string { return proto.CompactTextString(m) }
func (*StateChangeControl) ProtoMessage()    {}
func (*StateChangeControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{5}
}
func (m *StateChangeControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangeControl.Unmarshal(m, b)
}
func (m *StateChangeControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangeControl.Marshal(b, m, deterministic)
}
func (m *StateChangeControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangeControl.Merge(m, src)
}
func (m *StateChangeControl) XXX_Size() int {
	return xxx_messageInfo_StateChangeControl.Size(m)
}
func (m *StateChangeControl) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangeControl.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangeControl proto.InternalMessageInfo

func (m *StateChangeControl) GetType() StateChangeControl_Type {
	if m != nil {
		return m.Type
	}
	return StateChangeControl_CREATE
}

func (m *StateChangeControl) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *StateChangeControl) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EventControl struct {
	Type EventControl_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.EventControl_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*EventControl_StateChangeControl
	//	*EventControl_MutationControl
	//	*EventControl_DiscoveryEvent
	Event                isEventControl_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventControl) Reset()         { *m = EventControl{} }
func (m *EventControl) String() string { return proto.CompactTextString(m) }
func (*EventControl) ProtoMessage()    {}
func (*EventControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{6}
}
func (m *EventControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventControl.Unmarshal(m, b)
}
func (m *EventControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventControl.Marshal(b, m, deterministic)
}
func (m *EventControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventControl.Merge(m, src)
}
func (m *EventControl) XXX_Size() int {
	return xxx_messageInfo_EventControl.Size(m)
}
func (m *EventControl) XXX_DiscardUnknown() {
	xxx_messageInfo_EventControl.DiscardUnknown(m)
}

var xxx_messageInfo_EventControl proto.InternalMessageInfo

type isEventControl_Event interface {
	isEventControl_Event()
}

type EventControl_StateChangeControl struct {
	StateChangeControl *StateChangeControl `protobuf:"bytes,2,opt,name=stateChangeControl,proto3,oneof" json:"stateChangeControl,omitempty"`
}
type EventControl_MutationControl struct {
	MutationControl *MutationControl `protobuf:"bytes,3,opt,name=mutationControl,proto3,oneof" json:"mutationControl,omitempty"`
}
type EventControl_DiscoveryEvent struct {
	DiscoveryEvent *DiscoveryEvent `protobuf:"bytes,4,opt,name=discoveryEvent,proto3,oneof" json:"discoveryEvent,omitempty"`
}

func (*EventControl_StateChangeControl) isEventControl_Event() {}
func (*EventControl_MutationControl) isEventControl_Event()    {}
func (*EventControl_DiscoveryEvent) isEventControl_Event()     {}

func (m *EventControl) GetEvent() isEventControl_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventControl) GetType() EventControl_Type {
	if m != nil {
		return m.Type
	}
	return EventControl_StateChange
}

func (m *EventControl) GetStateChangeControl() *StateChangeControl {
	if x, ok := m.GetEvent().(*EventControl_StateChangeControl); ok {
		return x.StateChangeControl
	}
	return nil
}

func (m *EventControl) GetMutationControl() *MutationControl {
	if x, ok := m.GetEvent().(*EventControl_MutationControl); ok {
		return x.MutationControl
	}
	return nil
}

func (m *EventControl) GetDiscoveryEvent() *DiscoveryEvent {
	if x, ok := m.GetEvent().(*EventControl_DiscoveryEvent); ok {
		return x.DiscoveryEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventControl) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventControl_StateChangeControl)(nil),
		(*EventControl_MutationControl)(nil),
		(*EventControl_DiscoveryEvent)(nil),
	}
}

type DiscoveryEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ValueId              string   `protobuf:"bytes,3,opt,name=value_id,json=valueId,proto3" json:"value_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryEvent) Reset()         { *m = DiscoveryEvent{} }
func (m *DiscoveryEvent) String() string { return proto.CompactTextString(m) }
func (*DiscoveryEvent) ProtoMessage()    {}
func (*DiscoveryEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{7}
}
func (m *DiscoveryEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryEvent.Unmarshal(m, b)
}
func (m *DiscoveryEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryEvent.Marshal(b, m, deterministic)
}
func (m *DiscoveryEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryEvent.Merge(m, src)
}
func (m *DiscoveryEvent) XXX_Size() int {
	return xxx_messageInfo_DiscoveryEvent.Size(m)
}
func (m *DiscoveryEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryEvent proto.InternalMessageInfo

func (m *DiscoveryEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiscoveryEvent) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DiscoveryEvent) GetValueId() string {
	if m != nil {
		return m.ValueId
	}
	return ""
}

type MutationNodeList struct {
	MutationNodeList     []*MutationNode `protobuf:"bytes,1,rep,name=MutationNodeList,proto3" json:"MutationNodeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MutationNodeList) Reset()         { *m = MutationNodeList{} }
func (m *MutationNodeList) String() string { return proto.CompactTextString(m) }
func (*MutationNodeList) ProtoMessage()    {}
func (*MutationNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{8}
}
func (m *MutationNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationNodeList.Unmarshal(m, b)
}
func (m *MutationNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationNodeList.Marshal(b, m, deterministic)
}
func (m *MutationNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationNodeList.Merge(m, src)
}
func (m *MutationNodeList) XXX_Size() int {
	return xxx_messageInfo_MutationNodeList.Size(m)
}
func (m *MutationNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_MutationNodeList proto.InternalMessageInfo

func (m *MutationNodeList) GetMutationNodeList() []*MutationNode {
	if m != nil {
		return m.MutationNodeList
	}
	return nil
}

type MutationEdgeList struct {
	MutationEdgeList     []*MutationEdge `protobuf:"bytes,1,rep,name=MutationEdgeList,proto3" json:"MutationEdgeList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MutationEdgeList) Reset()         { *m = MutationEdgeList{} }
func (m *MutationEdgeList) String() string { return proto.CompactTextString(m) }
func (*MutationEdgeList) ProtoMessage()    {}
func (*MutationEdgeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{9}
}
func (m *MutationEdgeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationEdgeList.Unmarshal(m, b)
}
func (m *MutationEdgeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationEdgeList.Marshal(b, m, deterministic)
}
func (m *MutationEdgeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationEdgeList.Merge(m, src)
}
func (m *MutationEdgeList) XXX_Size() int {
	return xxx_messageInfo_MutationEdgeList.Size(m)
}
func (m *MutationEdgeList) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationEdgeList.DiscardUnknown(m)
}

var xxx_messageInfo_MutationEdgeList proto.InternalMessageInfo

func (m *MutationEdgeList) GetMutationEdgeList() []*MutationEdge {
	if m != nil {
		return m.MutationEdgeList
	}
	return nil
}

type MutationPath struct {
	Cur                  int64           `protobuf:"varint,1,opt,name=cur,proto3" json:"cur,omitempty"`
	Cmplt                bool            `protobuf:"varint,2,opt,name=cmplt,proto3" json:"cmplt,omitempty"`
	Chain                []*MutationEdge `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MutationPath) Reset()         { *m = MutationPath{} }
func (m *MutationPath) String() string { return proto.CompactTextString(m) }
func (*MutationPath) ProtoMessage()    {}
func (*MutationPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{10}
}
func (m *MutationPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationPath.Unmarshal(m, b)
}
func (m *MutationPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationPath.Marshal(b, m, deterministic)
}
func (m *MutationPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationPath.Merge(m, src)
}
func (m *MutationPath) XXX_Size() int {
	return xxx_messageInfo_MutationPath.Size(m)
}
func (m *MutationPath) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationPath.DiscardUnknown(m)
}

var xxx_messageInfo_MutationPath proto.InternalMessageInfo

func (m *MutationPath) GetCur() int64 {
	if m != nil {
		return m.Cur
	}
	return 0
}

func (m *MutationPath) GetCmplt() bool {
	if m != nil {
		return m.Cmplt
	}
	return false
}

func (m *MutationPath) GetChain() []*MutationEdge {
	if m != nil {
		return m.Chain
	}
	return nil
}

type MutationNode struct {
	Label                string     `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Id                   string     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Color                *NodeColor `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MutationNode) Reset()         { *m = MutationNode{} }
func (m *MutationNode) String() string { return proto.CompactTextString(m) }
func (*MutationNode) ProtoMessage()    {}
func (*MutationNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{11}
}
func (m *MutationNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationNode.Unmarshal(m, b)
}
func (m *MutationNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationNode.Marshal(b, m, deterministic)
}
func (m *MutationNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationNode.Merge(m, src)
}
func (m *MutationNode) XXX_Size() int {
	return xxx_messageInfo_MutationNode.Size(m)
}
func (m *MutationNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationNode.DiscardUnknown(m)
}

var xxx_messageInfo_MutationNode proto.InternalMessageInfo

func (m *MutationNode) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *MutationNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MutationNode) GetColor() *NodeColor {
	if m != nil {
		return m.Color
	}
	return nil
}

type MutationEdge struct {
	From                 string     `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string     `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Color                *EdgeColor `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MutationEdge) Reset()         { *m = MutationEdge{} }
func (m *MutationEdge) String() string { return proto.CompactTextString(m) }
func (*MutationEdge) ProtoMessage()    {}
func (*MutationEdge) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{12}
}
func (m *MutationEdge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationEdge.Unmarshal(m, b)
}
func (m *MutationEdge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationEdge.Marshal(b, m, deterministic)
}
func (m *MutationEdge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationEdge.Merge(m, src)
}
func (m *MutationEdge) XXX_Size() int {
	return xxx_messageInfo_MutationEdge.Size(m)
}
func (m *MutationEdge) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationEdge.DiscardUnknown(m)
}

var xxx_messageInfo_MutationEdge proto.InternalMessageInfo

func (m *MutationEdge) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MutationEdge) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MutationEdge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MutationEdge) GetColor() *EdgeColor {
	if m != nil {
		return m.Color
	}
	return nil
}

// This is only nessessary for the json mutation edge color to output in the correct format for the dashboard
type EdgeColor struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Highlight            string   `protobuf:"bytes,2,opt,name=highlight,proto3" json:"highlight,omitempty"`
	Inherit              bool     `protobuf:"varint,3,opt,name=inherit,proto3" json:"inherit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeColor) Reset()         { *m = EdgeColor{} }
func (m *EdgeColor) String() string { return proto.CompactTextString(m) }
func (*EdgeColor) ProtoMessage()    {}
func (*EdgeColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{13}
}
func (m *EdgeColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeColor.Unmarshal(m, b)
}
func (m *EdgeColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeColor.Marshal(b, m, deterministic)
}
func (m *EdgeColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeColor.Merge(m, src)
}
func (m *EdgeColor) XXX_Size() int {
	return xxx_messageInfo_EdgeColor.Size(m)
}
func (m *EdgeColor) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeColor.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeColor proto.InternalMessageInfo

func (m *EdgeColor) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *EdgeColor) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *EdgeColor) GetInherit() bool {
	if m != nil {
		return m.Inherit
	}
	return false
}

// This is only nessessary for the json mutation node color to output in the correct format for the dashboard
type NodeColor struct {
	Border               string   `protobuf:"bytes,1,opt,name=border,proto3" json:"border,omitempty"`
	Background           string   `protobuf:"bytes,2,opt,name=background,proto3" json:"background,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeColor) Reset()         { *m = NodeColor{} }
func (m *NodeColor) String() string { return proto.CompactTextString(m) }
func (*NodeColor) ProtoMessage()    {}
func (*NodeColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{14}
}
func (m *NodeColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeColor.Unmarshal(m, b)
}
func (m *NodeColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeColor.Marshal(b, m, deterministic)
}
func (m *NodeColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeColor.Merge(m, src)
}
func (m *NodeColor) XXX_Size() int {
	return xxx_messageInfo_NodeColor.Size(m)
}
func (m *NodeColor) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeColor.DiscardUnknown(m)
}

var xxx_messageInfo_NodeColor proto.InternalMessageInfo

func (m *NodeColor) GetBorder() string {
	if m != nil {
		return m.Border
	}
	return ""
}

func (m *NodeColor) GetBackground() string {
	if m != nil {
		return m.Background
	}
	return ""
}

type LogMessage struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Level                uint32   `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0480c644eb8bb9b4, []int{15}
}
func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *LogMessage) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.ServiceControl_Command", ServiceControl_Command_name, ServiceControl_Command_value)
	proto.RegisterEnum("proto.MutationControl_Type", MutationControl_Type_name, MutationControl_Type_value)
	proto.RegisterEnum("proto.StateChangeControl_Type", StateChangeControl_Type_name, StateChangeControl_Type_value)
	proto.RegisterEnum("proto.EventControl_Type", EventControl_Type_name, EventControl_Type_value)
	proto.RegisterType((*Query)(nil), "proto.Query")
	proto.RegisterType((*QueryMulti)(nil), "proto.QueryMulti")
	proto.RegisterType((*ServiceInitRequest)(nil), "proto.ServiceInitRequest")
	proto.RegisterType((*ServiceControl)(nil), "proto.ServiceControl")
	proto.RegisterType((*MutationControl)(nil), "proto.MutationControl")
	proto.RegisterType((*StateChangeControl)(nil), "proto.StateChangeControl")
	proto.RegisterType((*EventControl)(nil), "proto.EventControl")
	proto.RegisterType((*DiscoveryEvent)(nil), "proto.DiscoveryEvent")
	proto.RegisterType((*MutationNodeList)(nil), "proto.MutationNodeList")
	proto.RegisterType((*MutationEdgeList)(nil), "proto.MutationEdgeList")
	proto.RegisterType((*MutationPath)(nil), "proto.MutationPath")
	proto.RegisterType((*MutationNode)(nil), "proto.MutationNode")
	proto.RegisterType((*MutationEdge)(nil), "proto.MutationEdge")
	proto.RegisterType((*EdgeColor)(nil), "proto.EdgeColor")
	proto.RegisterType((*NodeColor)(nil), "proto.NodeColor")
	proto.RegisterType((*LogMessage)(nil), "proto.LogMessage")
}

func init() { proto.RegisterFile("ModuleAPI.proto", fileDescriptor_0480c644eb8bb9b4) }

var fileDescriptor_0480c644eb8bb9b4 = []byte{
	// 1229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x96, 0xfc, 0x13, 0x5b, 0xc7, 0xae, 0x23, 0xb6, 0x49, 0x70, 0x5c, 0xda, 0x49, 0x75, 0xd1,
	0x49, 0x86, 0x8c, 0xc3, 0xb8, 0x2d, 0x0c, 0x93, 0x42, 0x26, 0xb1, 0x55, 0xec, 0x21, 0x0e, 0x61,
	0xe3, 0x5c, 0xc0, 0x30, 0xd3, 0x51, 0xa4, 0x8d, 0x2c, 0x90, 0xb5, 0xae, 0x24, 0x07, 0xdc, 0xc7,
	0xe1, 0x39, 0xb8, 0xe4, 0x8e, 0xe1, 0x49, 0x78, 0x09, 0x66, 0x57, 0x2b, 0x5b, 0xb2, 0xec, 0x38,
	0xbd, 0xd2, 0x9e, 0xbf, 0xef, 0xfc, 0xea, 0xec, 0xc2, 0x66, 0x9f, 0x5a, 0x13, 0x97, 0x9c, 0x5e,
	0xf6, 0x9a, 0x63, 0x9f, 0x86, 0x14, 0x15, 0xf9, 0xa7, 0x01, 0x17, 0xd4, 0x22, 0x11, 0xab, 0xb1,
	0x6b, 0x53, 0x6a, 0xbb, 0xe4, 0x88, 0x53, 0x37, 0x93, 0xdb, 0x23, 0xc3, 0x9b, 0x0a, 0xd1, 0x93,
	0x45, 0x91, 0x3e, 0x1a, 0x87, 0x42, 0xa8, 0xfd, 0x95, 0x83, 0xe2, 0x8f, 0x13, 0xe2, 0x4f, 0x91,
	0x0a, 0xf9, 0x6b, 0x7c, 0x5e, 0x97, 0xf7, 0xe4, 0x7d, 0x05, 0xb3, 0x23, 0x7a, 0x0e, 0x05, 0x8f,
	0x5a, 0xa4, 0x9e, 0xdb, 0x93, 0xf7, 0x2b, 0xad, 0x4a, 0x64, 0xd1, 0x64, 0x4e, 0xbb, 0x12, 0xe6,
	0x22, 0xb4, 0x05, 0x85, 0x90, 0xfc, 0x11, 0xd6, 0xf3, 0xcc, 0x8a, 0x71, 0x19, 0xc5, 0xb8, 0x37,
	0x94, 0xba, 0xf5, 0xc2, 0x9e, 0xbc, 0x5f, 0x66, 0x5c, 0x46, 0x21, 0x1d, 0xd4, 0xd1, 0x24, 0x34,
	0x42, 0x87, 0x7a, 0x0c, 0xe3, 0xdc, 0x09, 0xc2, 0x7a, 0x91, 0x43, 0x7f, 0x2a, 0xa0, 0xfb, 0x0b,
	0xe2, 0xae, 0x84, 0x33, 0x26, 0x49, 0x18, 0xdd, 0xb2, 0x23, 0x98, 0x8d, 0xa5, 0x30, 0xb1, 0x38,
	0x09, 0x13, 0xf3, 0xd0, 0xd7, 0x50, 0x8d, 0x79, 0x97, 0x46, 0x38, 0xac, 0x97, 0x38, 0xc4, 0xe3,
	0x05, 0x08, 0x26, 0xea, 0x4a, 0x38, 0xa5, 0x7a, 0xa6, 0x40, 0x69, 0x6c, 0x4c, 0x5d, 0x6a, 0x58,
	0xda, 0x2b, 0x00, 0x5e, 0xbd, 0xfe, 0xc4, 0x0d, 0x1d, 0xf4, 0x02, 0x4a, 0xef, 0x27, 0xc4, 0x77,
	0x48, 0x50, 0x97, 0xf7, 0xf2, 0xfb, 0x95, 0x56, 0x55, 0xc0, 0x71, 0x1d, 0x1c, 0x0b, 0xb5, 0x37,
	0x80, 0xae, 0x88, 0x7f, 0xe7, 0x98, 0xa4, 0xe7, 0x39, 0x21, 0x26, 0xef, 0x27, 0x24, 0x08, 0x51,
	0x0d, 0x72, 0x8e, 0x25, 0xea, 0x9f, 0x73, 0x2c, 0xb4, 0x03, 0x1b, 0x23, 0xde, 0x78, 0xde, 0x00,
	0x05, 0x0b, 0x4a, 0xfb, 0x53, 0x86, 0x9a, 0x30, 0x6f, 0x53, 0x2f, 0xf4, 0xa9, 0x8b, 0xbe, 0x82,
	0x92, 0x49, 0x47, 0x23, 0xc3, 0x8b, 0xec, 0x6b, 0xad, 0xa7, 0xc2, 0x71, 0x5a, 0xaf, 0xd9, 0x8e,
	0x94, 0x70, 0xac, 0x8d, 0x0e, 0x61, 0xc3, 0xa4, 0xde, 0xad, 0x63, 0x8b, 0x26, 0x6f, 0x35, 0xa3,
	0x61, 0x69, 0xc6, 0xc3, 0xd2, 0x3c, 0xf5, 0xa6, 0x58, 0xe8, 0x68, 0x07, 0x50, 0x12, 0x08, 0xa8,
	0x0c, 0x85, 0xab, 0xc1, 0x0f, 0x97, 0xaa, 0x84, 0x00, 0x36, 0xae, 0x2f, 0x3b, 0xa7, 0x03, 0x5d,
	0x95, 0x19, 0xb7, 0x77, 0xd1, 0x1b, 0xa8, 0x39, 0xed, 0x1f, 0x19, 0x36, 0xe3, 0x22, 0xc6, 0x51,
	0xce, 0x13, 0x92, 0x93, 0x09, 0x89, 0xc4, 0x73, 0xb3, 0xc4, 0x8f, 0xa0, 0x10, 0x4e, 0xc7, 0x84,
	0x0f, 0x55, 0xad, 0xf5, 0x64, 0xa1, 0x25, 0x71, 0x2e, 0x83, 0xe9, 0x98, 0x60, 0xae, 0x88, 0x9e,
	0x42, 0xde, 0xbc, 0xb5, 0xf9, 0xb8, 0xa5, 0xe7, 0x14, 0x33, 0x3e, 0x13, 0x5b, 0x81, 0x29, 0x66,
	0x2d, 0x2d, 0xb6, 0x02, 0x53, 0x7b, 0x0e, 0x05, 0x86, 0xc5, 0x12, 0xe9, 0x5f, 0x0f, 0x58, 0x22,
	0x12, 0x7a, 0x04, 0x4a, 0xef, 0x62, 0xa0, 0x63, 0x7c, 0x7d, 0x39, 0x50, 0x65, 0xed, 0x6f, 0x19,
	0xd0, 0x55, 0x68, 0x84, 0xa4, 0x3d, 0x34, 0x3c, 0x7b, 0x56, 0xf6, 0x96, 0x08, 0x34, 0xaa, 0xf9,
	0xb3, 0xb8, 0xe6, 0x19, 0xc5, 0x64, 0xac, 0x2a, 0xe4, 0x27, 0xbe, 0x2b, 0xb2, 0x65, 0x47, 0xb4,
	0x05, 0xc5, 0x3b, 0xc3, 0x9d, 0x44, 0xf9, 0x2a, 0x38, 0x22, 0x34, 0x3c, 0x8f, 0xaa, 0x8d, 0xf5,
	0x28, 0xaa, 0x32, 0x14, 0xb0, 0x7e, 0xda, 0x51, 0xe5, 0x44, 0xd1, 0x73, 0xec, 0xdc, 0xd1, 0xcf,
	0xf5, 0x81, 0xae, 0xe6, 0x51, 0x15, 0xca, 0xed, 0xb7, 0xdf, 0xbd, 0xe3, 0x5a, 0x05, 0x54, 0x03,
	0x60, 0x94, 0xd0, 0x2c, 0x6a, 0xff, 0xe6, 0xa0, 0xaa, 0xdf, 0x11, 0x2f, 0x8c, 0x13, 0x38, 0x4c,
	0x25, 0x50, 0x17, 0x09, 0x24, 0x55, 0x92, 0xa1, 0x7f, 0x0f, 0x28, 0xc8, 0xe4, 0x26, 0x06, 0x67,
	0x77, 0x65, 0xf2, 0x5d, 0x09, 0x2f, 0x31, 0x43, 0x67, 0xb0, 0x39, 0x4a, 0x77, 0x94, 0xe7, 0x5f,
	0x69, 0xed, 0x2c, 0xef, 0x77, 0x57, 0xc2, 0x8b, 0x06, 0xe8, 0x04, 0x6a, 0x96, 0x13, 0x98, 0xf4,
	0x8e, 0xf8, 0x53, 0x1e, 0xb4, 0x18, 0x81, 0x6d, 0x01, 0xd1, 0x49, 0x09, 0xbb, 0x12, 0x5e, 0x50,
	0xd7, 0x5e, 0x89, 0x22, 0x6f, 0x42, 0x25, 0x11, 0xb8, 0x2a, 0xb1, 0x3a, 0xc6, 0xfe, 0x55, 0x99,
	0x4d, 0xc3, 0x0c, 0x4a, 0xcd, 0x9d, 0x95, 0xa0, 0x48, 0xb8, 0x79, 0x1f, 0x6a, 0x69, 0x17, 0x99,
	0x7f, 0x38, 0xdb, 0xed, 0x5d, 0x28, 0xf3, 0x06, 0xbf, 0x73, 0x2c, 0xd1, 0xf0, 0x12, 0xa7, 0x7b,
	0x96, 0x76, 0x05, 0xea, 0xe2, 0x06, 0x44, 0x27, 0x59, 0x9e, 0xd8, 0x2d, 0x8f, 0x97, 0x2c, 0x4d,
	0x9c, 0x51, 0x4e, 0x82, 0xce, 0x76, 0xdf, 0x49, 0x96, 0xb7, 0x02, 0x94, 0x89, 0x71, 0x46, 0x59,
	0x33, 0xa0, 0x9a, 0xdc, 0x90, 0x2c, 0x4d, 0x73, 0xe2, 0xf3, 0xbc, 0xf3, 0x98, 0x1d, 0xd9, 0x50,
	0x9b, 0xa3, 0xb1, 0x1b, 0xf2, 0xd4, 0xcb, 0x38, 0x22, 0xd0, 0x01, 0x14, 0xcd, 0xa1, 0xe1, 0x78,
	0xf5, 0xfc, 0x6a, 0x6f, 0x91, 0x86, 0xf6, 0xcb, 0xdc, 0xc5, 0x45, 0x74, 0xd3, 0x14, 0x5d, 0xe3,
	0x86, 0xb8, 0xa2, 0xb8, 0x11, 0x91, 0x59, 0x1d, 0x2f, 0xa0, 0x68, 0x52, 0x97, 0xfa, 0x62, 0x96,
	0xd4, 0xc4, 0xcf, 0xde, 0x66, 0x7c, 0x1c, 0x89, 0xb5, 0x5f, 0xe7, 0xe8, 0xcc, 0x29, 0x42, 0x50,
	0xb8, 0xf5, 0xe9, 0x48, 0x80, 0xf3, 0x33, 0xc3, 0x0e, 0x69, 0x8c, 0x1d, 0x52, 0xe1, 0x2b, 0x9f,
	0xf5, 0x55, 0x48, 0xf9, 0x62, 0x78, 0x29, 0x5f, 0x3f, 0x81, 0x32, 0xe3, 0xf1, 0xba, 0x70, 0x23,
	0x91, 0x06, 0x27, 0xd0, 0x67, 0xa0, 0x0c, 0x1d, 0x7b, 0xe8, 0x3a, 0xf6, 0x30, 0x14, 0x1e, 0xe7,
	0x0c, 0x54, 0x87, 0x92, 0xe3, 0x0d, 0x89, 0xef, 0x44, 0xf7, 0x6c, 0x19, 0xc7, 0xa4, 0xd6, 0x06,
	0x65, 0x96, 0x1a, 0x5b, 0xaf, 0x37, 0xd4, 0xb7, 0x48, 0x8c, 0x2d, 0x28, 0xf4, 0x0c, 0xe0, 0xc6,
	0x30, 0x7f, 0xb3, 0x7d, 0x3a, 0xf1, 0xe2, 0x5a, 0x25, 0x38, 0xda, 0x39, 0xc0, 0x39, 0xb5, 0xfb,
	0x24, 0x08, 0x0c, 0x9b, 0x30, 0x14, 0xea, 0x3b, 0xb6, 0xe3, 0xc5, 0x28, 0x11, 0xc5, 0xeb, 0x4f,
	0xee, 0x48, 0x34, 0xcb, 0x8f, 0x70, 0x44, 0xb0, 0xc6, 0x8f, 0x02, 0x5b, 0x14, 0x85, 0x1d, 0x5b,
	0xff, 0x29, 0xa0, 0xcc, 0xde, 0x2b, 0xe8, 0x73, 0xa8, 0xf0, 0xbb, 0xaf, 0xed, 0x13, 0x23, 0x24,
	0x28, 0x75, 0x1f, 0x36, 0x52, 0x94, 0x26, 0xa1, 0x03, 0x50, 0xa2, 0x8b, 0x92, 0x18, 0xd6, 0x1a,
	0xd5, 0x43, 0xa8, 0xce, 0x54, 0x3b, 0x81, 0xb9, 0x46, 0x3b, 0x8e, 0xe2, 0x7a, 0x6c, 0xad, 0x8f,
	0xa2, 0x09, 0xb5, 0x84, 0xf2, 0xc3, 0xc1, 0x3b, 0xc4, 0x25, 0x6b, 0xc1, 0x8f, 0x13, 0x71, 0x9f,
	0xba, 0x2e, 0xda, 0xc9, 0xdc, 0xb7, 0xfc, 0x71, 0xd6, 0xf8, 0x24, 0x69, 0xc7, 0x1f, 0x17, 0x9a,
	0x84, 0xbe, 0x85, 0xcd, 0xa4, 0x31, 0x0b, 0xed, 0xa3, 0xec, 0xdf, 0x00, 0x12, 0xf4, 0xfc, 0xbf,
	0x0a, 0x56, 0x42, 0x2c, 0x86, 0xbe, 0x68, 0xcd, 0x66, 0xfa, 0xe1, 0xd6, 0x5f, 0xc2, 0x0e, 0x3f,
	0x32, 0x9f, 0x69, 0xff, 0xf7, 0x17, 0x6c, 0x99, 0x5d, 0xe4, 0xf9, 0x7e, 0xbb, 0xd7, 0xb0, 0x9d,
	0xb1, 0xe3, 0xab, 0xea, 0x7e, 0xb3, 0x6f, 0x44, 0xf3, 0xa3, 0x66, 0x7e, 0x74, 0x87, 0x5e, 0x8b,
	0x59, 0x78, 0xeb, 0x13, 0xf2, 0x81, 0x3c, 0xb8, 0x38, 0x2f, 0xc5, 0xe0, 0x0f, 0x86, 0xc6, 0xef,
	0x0f, 0x36, 0x9a, 0xfb, 0xa2, 0x1f, 0x88, 0xf7, 0x60, 0xb3, 0x36, 0x54, 0x12, 0x6f, 0x4f, 0xb4,
	0x9b, 0x7e, 0x28, 0x26, 0xde, 0xa3, 0x8d, 0xed, 0xa5, 0x6f, 0x48, 0x4d, 0xfa, 0x42, 0x46, 0xfa,
	0x7c, 0x7d, 0xae, 0x43, 0x59, 0x71, 0x9d, 0x73, 0x98, 0x13, 0x50, 0xf8, 0xb5, 0xb9, 0x0e, 0xe3,
	0xf1, 0x92, 0x87, 0x09, 0x07, 0x38, 0x83, 0x47, 0xb3, 0x0b, 0x98, 0x83, 0x2c, 0xbf, 0xf9, 0x1b,
	0x2b, 0x8a, 0xa3, 0x49, 0xfb, 0x32, 0x3a, 0xe6, 0xeb, 0xcf, 0x26, 0x3e, 0x07, 0x88, 0xdb, 0x3a,
	0xdf, 0x88, 0xf7, 0x19, 0x9f, 0x29, 0x3f, 0x97, 0x9a, 0xc7, 0x11, 0x7f, 0x83, 0x7f, 0x5e, 0xfe,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x82, 0x6f, 0x26, 0x87, 0xae, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleAPIClient is the client API for ModuleAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleAPIClient interface {
	// Query language
	// TODO: create API for bulk CRUD operations
	QueryCreate(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryRead(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryReadDsc(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryUpdate(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryUpdateDsc(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryDelete(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryReadAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error)
	QueryReadAllDsc(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error)
	QueryMutationNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error)
	QueryMutationEdges(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error)
	QueryNodeMutationNodes(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryNodeMutationEdges(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryNodeMutationPath(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error)
	QueryDeleteAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error)
	QueryFreeze(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error)
	QueryThaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error)
	QueryFrozen(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error)
	// Service management
	ServiceInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_ServiceInitClient, error)
	// Mutation/Discover management
	MutationInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_MutationInitClient, error)
	// Event management
	EventInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_EventInitClient, error)
	// Discovery management
	DiscoveryInit(ctx context.Context, opts ...grpc.CallOption) (ModuleAPI_DiscoveryInitClient, error)
	// Logging
	LoggerInit(ctx context.Context, opts ...grpc.CallOption) (ModuleAPI_LoggerInitClient, error)
}

type moduleAPIClient struct {
	cc *grpc.ClientConn
}

func NewModuleAPIClient(cc *grpc.ClientConn) ModuleAPIClient {
	return &moduleAPIClient{cc}
}

func (c *moduleAPIClient) QueryCreate(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryRead(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryReadDsc(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryReadDsc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryUpdate(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryUpdateDsc(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryUpdateDsc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryDelete(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryReadAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error) {
	out := new(QueryMulti)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryReadAllDsc(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error) {
	out := new(QueryMulti)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryReadAllDsc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryMutationNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryMutationNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryMutationEdges(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryMutationEdges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryNodeMutationNodes(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryNodeMutationNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryNodeMutationEdges(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryNodeMutationEdges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryNodeMutationPath(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryNodeMutationPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryDeleteAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*QueryMulti, error) {
	out := new(QueryMulti)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryDeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryFreeze(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryFreeze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryThaw(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryThaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) QueryFrozen(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Query, error) {
	out := new(Query)
	err := c.cc.Invoke(ctx, "/proto.ModuleAPI/QueryFrozen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleAPIClient) ServiceInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_ServiceInitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleAPI_serviceDesc.Streams[0], "/proto.ModuleAPI/ServiceInit", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleAPIServiceInitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModuleAPI_ServiceInitClient interface {
	Recv() (*ServiceControl, error)
	grpc.ClientStream
}

type moduleAPIServiceInitClient struct {
	grpc.ClientStream
}

func (x *moduleAPIServiceInitClient) Recv() (*ServiceControl, error) {
	m := new(ServiceControl)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moduleAPIClient) MutationInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_MutationInitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleAPI_serviceDesc.Streams[1], "/proto.ModuleAPI/MutationInit", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleAPIMutationInitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModuleAPI_MutationInitClient interface {
	Recv() (*MutationControl, error)
	grpc.ClientStream
}

type moduleAPIMutationInitClient struct {
	grpc.ClientStream
}

func (x *moduleAPIMutationInitClient) Recv() (*MutationControl, error) {
	m := new(MutationControl)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moduleAPIClient) EventInit(ctx context.Context, in *ServiceInitRequest, opts ...grpc.CallOption) (ModuleAPI_EventInitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleAPI_serviceDesc.Streams[2], "/proto.ModuleAPI/EventInit", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleAPIEventInitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModuleAPI_EventInitClient interface {
	Recv() (*EventControl, error)
	grpc.ClientStream
}

type moduleAPIEventInitClient struct {
	grpc.ClientStream
}

func (x *moduleAPIEventInitClient) Recv() (*EventControl, error) {
	m := new(EventControl)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moduleAPIClient) DiscoveryInit(ctx context.Context, opts ...grpc.CallOption) (ModuleAPI_DiscoveryInitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleAPI_serviceDesc.Streams[3], "/proto.ModuleAPI/DiscoveryInit", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleAPIDiscoveryInitClient{stream}
	return x, nil
}

type ModuleAPI_DiscoveryInitClient interface {
	Send(*DiscoveryEvent) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type moduleAPIDiscoveryInitClient struct {
	grpc.ClientStream
}

func (x *moduleAPIDiscoveryInitClient) Send(m *DiscoveryEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *moduleAPIDiscoveryInitClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moduleAPIClient) LoggerInit(ctx context.Context, opts ...grpc.CallOption) (ModuleAPI_LoggerInitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModuleAPI_serviceDesc.Streams[4], "/proto.ModuleAPI/LoggerInit", opts...)
	if err != nil {
		return nil, err
	}
	x := &moduleAPILoggerInitClient{stream}
	return x, nil
}

type ModuleAPI_LoggerInitClient interface {
	Send(*LogMessage) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type moduleAPILoggerInitClient struct {
	grpc.ClientStream
}

func (x *moduleAPILoggerInitClient) Send(m *LogMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *moduleAPILoggerInitClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ModuleAPIServer is the server API for ModuleAPI service.
type ModuleAPIServer interface {
	// Query language
	// TODO: create API for bulk CRUD operations
	QueryCreate(context.Context, *Query) (*Query, error)
	QueryRead(context.Context, *Query) (*Query, error)
	QueryReadDsc(context.Context, *Query) (*Query, error)
	QueryUpdate(context.Context, *Query) (*Query, error)
	QueryUpdateDsc(context.Context, *Query) (*Query, error)
	QueryDelete(context.Context, *Query) (*Query, error)
	QueryReadAll(context.Context, *empty.Empty) (*QueryMulti, error)
	QueryReadAllDsc(context.Context, *empty.Empty) (*QueryMulti, error)
	QueryMutationNodes(context.Context, *empty.Empty) (*Query, error)
	QueryMutationEdges(context.Context, *empty.Empty) (*Query, error)
	QueryNodeMutationNodes(context.Context, *Query) (*Query, error)
	QueryNodeMutationEdges(context.Context, *Query) (*Query, error)
	QueryNodeMutationPath(context.Context, *Query) (*Query, error)
	QueryDeleteAll(context.Context, *empty.Empty) (*QueryMulti, error)
	QueryFreeze(context.Context, *empty.Empty) (*Query, error)
	QueryThaw(context.Context, *empty.Empty) (*Query, error)
	QueryFrozen(context.Context, *empty.Empty) (*Query, error)
	// Service management
	ServiceInit(*ServiceInitRequest, ModuleAPI_ServiceInitServer) error
	// Mutation/Discover management
	MutationInit(*ServiceInitRequest, ModuleAPI_MutationInitServer) error
	// Event management
	EventInit(*ServiceInitRequest, ModuleAPI_EventInitServer) error
	// Discovery management
	DiscoveryInit(ModuleAPI_DiscoveryInitServer) error
	// Logging
	LoggerInit(ModuleAPI_LoggerInitServer) error
}

// UnimplementedModuleAPIServer can be embedded to have forward compatible implementations.
type UnimplementedModuleAPIServer struct {
}

func (*UnimplementedModuleAPIServer) QueryCreate(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCreate not implemented")
}
func (*UnimplementedModuleAPIServer) QueryRead(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRead not implemented")
}
func (*UnimplementedModuleAPIServer) QueryReadDsc(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReadDsc not implemented")
}
func (*UnimplementedModuleAPIServer) QueryUpdate(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUpdate not implemented")
}
func (*UnimplementedModuleAPIServer) QueryUpdateDsc(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUpdateDsc not implemented")
}
func (*UnimplementedModuleAPIServer) QueryDelete(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDelete not implemented")
}
func (*UnimplementedModuleAPIServer) QueryReadAll(ctx context.Context, req *empty.Empty) (*QueryMulti, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReadAll not implemented")
}
func (*UnimplementedModuleAPIServer) QueryReadAllDsc(ctx context.Context, req *empty.Empty) (*QueryMulti, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReadAllDsc not implemented")
}
func (*UnimplementedModuleAPIServer) QueryMutationNodes(ctx context.Context, req *empty.Empty) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMutationNodes not implemented")
}
func (*UnimplementedModuleAPIServer) QueryMutationEdges(ctx context.Context, req *empty.Empty) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMutationEdges not implemented")
}
func (*UnimplementedModuleAPIServer) QueryNodeMutationNodes(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNodeMutationNodes not implemented")
}
func (*UnimplementedModuleAPIServer) QueryNodeMutationEdges(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNodeMutationEdges not implemented")
}
func (*UnimplementedModuleAPIServer) QueryNodeMutationPath(ctx context.Context, req *Query) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNodeMutationPath not implemented")
}
func (*UnimplementedModuleAPIServer) QueryDeleteAll(ctx context.Context, req *empty.Empty) (*QueryMulti, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeleteAll not implemented")
}
func (*UnimplementedModuleAPIServer) QueryFreeze(ctx context.Context, req *empty.Empty) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFreeze not implemented")
}
func (*UnimplementedModuleAPIServer) QueryThaw(ctx context.Context, req *empty.Empty) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryThaw not implemented")
}
func (*UnimplementedModuleAPIServer) QueryFrozen(ctx context.Context, req *empty.Empty) (*Query, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFrozen not implemented")
}
func (*UnimplementedModuleAPIServer) ServiceInit(req *ServiceInitRequest, srv ModuleAPI_ServiceInitServer) error {
	return status.Errorf(codes.Unimplemented, "method ServiceInit not implemented")
}
func (*UnimplementedModuleAPIServer) MutationInit(req *ServiceInitRequest, srv ModuleAPI_MutationInitServer) error {
	return status.Errorf(codes.Unimplemented, "method MutationInit not implemented")
}
func (*UnimplementedModuleAPIServer) EventInit(req *ServiceInitRequest, srv ModuleAPI_EventInitServer) error {
	return status.Errorf(codes.Unimplemented, "method EventInit not implemented")
}
func (*UnimplementedModuleAPIServer) DiscoveryInit(srv ModuleAPI_DiscoveryInitServer) error {
	return status.Errorf(codes.Unimplemented, "method DiscoveryInit not implemented")
}
func (*UnimplementedModuleAPIServer) LoggerInit(srv ModuleAPI_LoggerInitServer) error {
	return status.Errorf(codes.Unimplemented, "method LoggerInit not implemented")
}

func RegisterModuleAPIServer(s *grpc.Server, srv ModuleAPIServer) {
	s.RegisterService(&_ModuleAPI_serviceDesc, srv)
}

func _ModuleAPI_QueryCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryCreate(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryRead(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryReadDsc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryReadDsc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryReadDsc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryReadDsc(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryUpdate(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryUpdateDsc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryUpdateDsc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryUpdateDsc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryUpdateDsc(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryDelete(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryReadAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryReadAllDsc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryReadAllDsc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryReadAllDsc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryReadAllDsc(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryMutationNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryMutationNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryMutationNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryMutationNodes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryMutationEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryMutationEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryMutationEdges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryMutationEdges(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryNodeMutationNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryNodeMutationNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryNodeMutationNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryNodeMutationNodes(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryNodeMutationEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryNodeMutationEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryNodeMutationEdges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryNodeMutationEdges(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryNodeMutationPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryNodeMutationPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryNodeMutationPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryNodeMutationPath(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryDeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryDeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryDeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryDeleteAll(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryFreeze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryFreeze(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryThaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryThaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryThaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryThaw(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_QueryFrozen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleAPIServer).QueryFrozen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ModuleAPI/QueryFrozen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleAPIServer).QueryFrozen(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleAPI_ServiceInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceInitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleAPIServer).ServiceInit(m, &moduleAPIServiceInitServer{stream})
}

type ModuleAPI_ServiceInitServer interface {
	Send(*ServiceControl) error
	grpc.ServerStream
}

type moduleAPIServiceInitServer struct {
	grpc.ServerStream
}

func (x *moduleAPIServiceInitServer) Send(m *ServiceControl) error {
	return x.ServerStream.SendMsg(m)
}

func _ModuleAPI_MutationInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceInitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleAPIServer).MutationInit(m, &moduleAPIMutationInitServer{stream})
}

type ModuleAPI_MutationInitServer interface {
	Send(*MutationControl) error
	grpc.ServerStream
}

type moduleAPIMutationInitServer struct {
	grpc.ServerStream
}

func (x *moduleAPIMutationInitServer) Send(m *MutationControl) error {
	return x.ServerStream.SendMsg(m)
}

func _ModuleAPI_EventInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceInitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleAPIServer).EventInit(m, &moduleAPIEventInitServer{stream})
}

type ModuleAPI_EventInitServer interface {
	Send(*EventControl) error
	grpc.ServerStream
}

type moduleAPIEventInitServer struct {
	grpc.ServerStream
}

func (x *moduleAPIEventInitServer) Send(m *EventControl) error {
	return x.ServerStream.SendMsg(m)
}

func _ModuleAPI_DiscoveryInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModuleAPIServer).DiscoveryInit(&moduleAPIDiscoveryInitServer{stream})
}

type ModuleAPI_DiscoveryInitServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*DiscoveryEvent, error)
	grpc.ServerStream
}

type moduleAPIDiscoveryInitServer struct {
	grpc.ServerStream
}

func (x *moduleAPIDiscoveryInitServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *moduleAPIDiscoveryInitServer) Recv() (*DiscoveryEvent, error) {
	m := new(DiscoveryEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ModuleAPI_LoggerInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModuleAPIServer).LoggerInit(&moduleAPILoggerInitServer{stream})
}

type ModuleAPI_LoggerInitServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*LogMessage, error)
	grpc.ServerStream
}

type moduleAPILoggerInitServer struct {
	grpc.ServerStream
}

func (x *moduleAPILoggerInitServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *moduleAPILoggerInitServer) Recv() (*LogMessage, error) {
	m := new(LogMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ModuleAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ModuleAPI",
	HandlerType: (*ModuleAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryCreate",
			Handler:    _ModuleAPI_QueryCreate_Handler,
		},
		{
			MethodName: "QueryRead",
			Handler:    _ModuleAPI_QueryRead_Handler,
		},
		{
			MethodName: "QueryReadDsc",
			Handler:    _ModuleAPI_QueryReadDsc_Handler,
		},
		{
			MethodName: "QueryUpdate",
			Handler:    _ModuleAPI_QueryUpdate_Handler,
		},
		{
			MethodName: "QueryUpdateDsc",
			Handler:    _ModuleAPI_QueryUpdateDsc_Handler,
		},
		{
			MethodName: "QueryDelete",
			Handler:    _ModuleAPI_QueryDelete_Handler,
		},
		{
			MethodName: "QueryReadAll",
			Handler:    _ModuleAPI_QueryReadAll_Handler,
		},
		{
			MethodName: "QueryReadAllDsc",
			Handler:    _ModuleAPI_QueryReadAllDsc_Handler,
		},
		{
			MethodName: "QueryMutationNodes",
			Handler:    _ModuleAPI_QueryMutationNodes_Handler,
		},
		{
			MethodName: "QueryMutationEdges",
			Handler:    _ModuleAPI_QueryMutationEdges_Handler,
		},
		{
			MethodName: "QueryNodeMutationNodes",
			Handler:    _ModuleAPI_QueryNodeMutationNodes_Handler,
		},
		{
			MethodName: "QueryNodeMutationEdges",
			Handler:    _ModuleAPI_QueryNodeMutationEdges_Handler,
		},
		{
			MethodName: "QueryNodeMutationPath",
			Handler:    _ModuleAPI_QueryNodeMutationPath_Handler,
		},
		{
			MethodName: "QueryDeleteAll",
			Handler:    _ModuleAPI_QueryDeleteAll_Handler,
		},
		{
			MethodName: "QueryFreeze",
			Handler:    _ModuleAPI_QueryFreeze_Handler,
		},
		{
			MethodName: "QueryThaw",
			Handler:    _ModuleAPI_QueryThaw_Handler,
		},
		{
			MethodName: "QueryFrozen",
			Handler:    _ModuleAPI_QueryFrozen_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceInit",
			Handler:       _ModuleAPI_ServiceInit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MutationInit",
			Handler:       _ModuleAPI_MutationInit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EventInit",
			Handler:       _ModuleAPI_EventInit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DiscoveryInit",
			Handler:       _ModuleAPI_DiscoveryInit_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LoggerInit",
			Handler:       _ModuleAPI_LoggerInit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ModuleAPI.proto",
}
