// Code generated by protoc-gen-go. DO NOT EDIT.
// source: powermancontrol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PMCConfig struct {
	Servers              map[string]*PMCServer `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PollingInterval      string                `protobuf:"bytes,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	FireInterval         string                `protobuf:"bytes,3,opt,name=fire_interval,json=fireInterval,proto3" json:"fire_interval,omitempty"`
	NameUrl              string                `protobuf:"bytes,4,opt,name=name_url,json=nameUrl,proto3" json:"name_url,omitempty"`
	ServerUrl            string                `protobuf:"bytes,5,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PMCConfig) Reset()         { *m = PMCConfig{} }
func (m *PMCConfig) String() string { return proto.CompactTextString(m) }
func (*PMCConfig) ProtoMessage()    {}
func (*PMCConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_powermancontrol_c68c4c9de3e1f41b, []int{0}
}
func (m *PMCConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMCConfig.Unmarshal(m, b)
}
func (m *PMCConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMCConfig.Marshal(b, m, deterministic)
}
func (dst *PMCConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMCConfig.Merge(dst, src)
}
func (m *PMCConfig) XXX_Size() int {
	return xxx_messageInfo_PMCConfig.Size(m)
}
func (m *PMCConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PMCConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PMCConfig proto.InternalMessageInfo

func (m *PMCConfig) GetServers() map[string]*PMCServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *PMCConfig) GetPollingInterval() string {
	if m != nil {
		return m.PollingInterval
	}
	return ""
}

func (m *PMCConfig) GetFireInterval() string {
	if m != nil {
		return m.FireInterval
	}
	return ""
}

func (m *PMCConfig) GetNameUrl() string {
	if m != nil {
		return m.NameUrl
	}
	return ""
}

func (m *PMCConfig) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

type PMCServer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PMCServer) Reset()         { *m = PMCServer{} }
func (m *PMCServer) String() string { return proto.CompactTextString(m) }
func (*PMCServer) ProtoMessage()    {}
func (*PMCServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_powermancontrol_c68c4c9de3e1f41b, []int{1}
}
func (m *PMCServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMCServer.Unmarshal(m, b)
}
func (m *PMCServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMCServer.Marshal(b, m, deterministic)
}
func (dst *PMCServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMCServer.Merge(dst, src)
}
func (m *PMCServer) XXX_Size() int {
	return xxx_messageInfo_PMCServer.Size(m)
}
func (m *PMCServer) XXX_DiscardUnknown() {
	xxx_messageInfo_PMCServer.DiscardUnknown(m)
}

var xxx_messageInfo_PMCServer proto.InternalMessageInfo

func (m *PMCServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PMCServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PMCServer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*PMCConfig)(nil), "proto.PMCConfig")
	proto.RegisterMapType((map[string]*PMCServer)(nil), "proto.PMCConfig.ServersEntry")
	proto.RegisterType((*PMCServer)(nil), "proto.PMCServer")
}

func init() {
	proto.RegisterFile("powermancontrol.proto", fileDescriptor_powermancontrol_c68c4c9de3e1f41b)
}

var fileDescriptor_powermancontrol_c68c4c9de3e1f41b = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xd2, 0x58, 0x33, 0xad, 0x1a, 0x06, 0x84, 0x28, 0x14, 0x4a, 0x05, 0xa9, 0x97,
	0x1c, 0xea, 0x41, 0xf1, 0x1a, 0x3c, 0x08, 0x0a, 0x12, 0xe9, 0xb9, 0x44, 0xd9, 0x96, 0xc5, 0xed,
	0xee, 0x32, 0xdd, 0x46, 0xfa, 0x5f, 0xfc, 0xb1, 0xb2, 0xb3, 0xb1, 0xed, 0x29, 0x93, 0xf7, 0xbe,
	0xdd, 0x79, 0x6f, 0xe1, 0xd2, 0x9a, 0x1f, 0x41, 0xeb, 0x46, 0x7f, 0x19, 0xed, 0xc8, 0xa8, 0xd2,
	0x92, 0x71, 0x06, 0x53, 0xfe, 0x4c, 0x7e, 0x63, 0xc8, 0xde, 0xdf, 0xaa, 0xca, 0xe8, 0xa5, 0x5c,
	0xe1, 0x03, 0xf4, 0x37, 0x82, 0x5a, 0x41, 0x9b, 0x22, 0x1a, 0x27, 0xd3, 0xc1, 0x6c, 0x14, 0xe8,
	0x72, 0x8f, 0x94, 0x1f, 0xc1, 0x7f, 0xd6, 0x8e, 0x76, 0xf5, 0x3f, 0x8d, 0x77, 0x90, 0x5b, 0xa3,
	0x94, 0xd4, 0xab, 0x85, 0xd4, 0x4e, 0x50, 0xdb, 0xa8, 0x22, 0x1e, 0x47, 0xd3, 0xac, 0xbe, 0xe8,
	0xf4, 0x97, 0x4e, 0xc6, 0x1b, 0x38, 0x5b, 0x4a, 0x12, 0x07, 0x2e, 0x61, 0x6e, 0xe8, 0xc5, 0x3d,
	0x74, 0x05, 0xa7, 0xba, 0x59, 0x8b, 0xc5, 0x96, 0x54, 0xd1, 0x63, 0xbf, 0xef, 0xff, 0xe7, 0xa4,
	0x70, 0x04, 0x10, 0xb6, 0xb2, 0x99, 0xb2, 0x99, 0x05, 0x65, 0x4e, 0xea, 0xfa, 0x15, 0x86, 0xc7,
	0x11, 0x31, 0x87, 0xe4, 0x5b, 0xec, 0x8a, 0x88, 0x39, 0x3f, 0xe2, 0x2d, 0xa4, 0x6d, 0xa3, 0xb6,
	0x82, 0x03, 0x0e, 0x66, 0xf9, 0xa1, 0x62, 0x38, 0x58, 0x07, 0xfb, 0x29, 0x7e, 0x8c, 0x26, 0x15,
	0xbf, 0x4e, 0xd0, 0x11, 0xa1, 0xe7, 0x43, 0x74, 0x77, 0xf1, 0x8c, 0xe7, 0x10, 0x4b, 0xdb, 0x55,
	0x8d, 0xa5, 0xf5, 0x8c, 0x35, 0xe4, 0xb8, 0x54, 0x5a, 0xf3, 0xfc, 0x79, 0xc2, 0x0b, 0xee, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x3f, 0x76, 0x85, 0x8a, 0x01, 0x00, 0x00,
}
