---
- name: Create Kraken configuration directory
  become: true
  file:
    path: "{{ kraken_cfgdir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

# note: we use copy here just so we can run through to_nice_json
- name: Generate Kraken state file
  become: true
  copy:
    content: "{{ lookup('template', 'nodes.json.j2') | to_nice_json }}"
    dest: "{{ kraken_state_file }}"
    owner: root
    group: root
    mode: 0644