# kraken-build.go: describes a build for a BitScope Raspberry Pi cluster
targets:
  'linux-arm64':  # this identifies the build, will be appended to the binary name
    os: 'linux'     # os must match a supported GOOS
    arch: 'arm64'   # arch must match a supported GOARCH
  'linux-amd64':
    os: 'linux'
    arch: 'amd64'
  'darwin-amd64':
    os: 'darwin'
    arch: 'amd64'

extensions:
  - github.com/kraken/extensions/IPv4
  - github.com/kraken/extensions/RPi3

instances: 
  - name: restapi
    module: github.com/kraken/modules/restapi
    config: # default configuration
      addr: '127.0.0.1'
      port: 3141

  - name: pipower 
    module: github.com/kraken/modules/pipower
    requires:   # these requires apply to all mutations
      '/Arch': 'aarch64'
      '/Platform': 'rpi3'
    excludes:   # these excluses apply to all mutations
    mutations:  # mutation names map to exports from the module
      'UKtoOFF':
        mutates:
          '/PhysState': { from: 'UNKNOWN', to: 'OFF' }
      'OFFtoON':
        mutates:
          '/PhysState': { from: 'OFF', to: 'ON' }
      'ONtoOFF':
        mutates:
          '/PhysState': { from: 'ON', to: 'OFF' }
