# kraken-build.go: describes a build for a Virtualbox testbed
targets:
  'linux-amd64':
    os: 'linux'
    arch: 'amd64'
  'darwin-amd64':
    os: 'darwin'
    arch: 'amd64'

# included extensions
extensions:
  - github.com/kraken-hpc/kraken/extensions/ipv4
  - github.com/kraken-hpc/kraken/extensions/powerman

# included modules
modules:
  - github.com/kraken-hpc/kraken/modules/restapi
  - github.com/kraken-hpc/kraken/modules/websocket
  - github.com/kraken-hpc/kraken/modules/powermancontrol