# kraken-build.go: describes a build for a Virtualbox testbed
targets:
  'linux-amd64':
    os: 'linux'
    arch: 'amd64'
  'darwin-amd64':
    os: 'darwin'
    arch: 'amd64'

# included extensions
extensions:
  - github.com/hpc/kraken/extensions/IPv4
  - github.com/hpc/kraken/extensions/Powerman

# included modules
modules:
  - github.com/hpc/kraken/modules/restapi
  - github.com/hpc/kraken/modules/websocket
  - github.com/hpc/kraken/modules/powermancontrol