# kraken-build.go: describes a build for a Virtualbox testbed
targets:
  'linux-arm64':
    os: 'linux'
    arch: 'arm64'

# included extensions
extensions:
  - github.com/hpc/kraken/extensions/IPv4

# included modules
modules:
  - github.com/hpc/kraken/modules/restapi
