# kraken-build.go: describes a build for embedding in UEFI firmware
targets:
  'u-root':

# included extensions
extensions:
  - github.com/hpc/kraken/extensions/IPv4
  - github.com/hpc/kraken/extensions/PXE

# included modules
modules:
  - github.com/hpc/kraken/modules/restapi
  - github.com/hpc/kraken/modules/websocket
  - github.com/hpc/kraken/modules/pxe
