// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hostfrequencyscaling.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HostFreqScalingConfig struct {
	FreqScalPolicies     map[string]*HostFreqScalingPolicy `protobuf:"bytes,1,rep,name=freq_scal_policies,json=freqScalPolicies,proto3" json:"freq_scal_policies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FreqSensorUrl        string                            `protobuf:"bytes,2,opt,name=freq_sensor_url,json=freqSensorUrl,proto3" json:"freq_sensor_url,omitempty"`
	BoottimeFreqPolicy   string                            `protobuf:"bytes,3,opt,name=boottime_freq_policy,json=boottimeFreqPolicy,proto3" json:"boottime_freq_policy,omitempty"`
	HightoLowFreqPolicy  string                            `protobuf:"bytes,4,opt,name=highto_low_freq_policy,json=hightoLowFreqPolicy,proto3" json:"highto_low_freq_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HostFreqScalingConfig) Reset()         { *m = HostFreqScalingConfig{} }
func (m *HostFreqScalingConfig) String() string { return proto.CompactTextString(m) }
func (*HostFreqScalingConfig) ProtoMessage()    {}
func (*HostFreqScalingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostfrequencyscaling_b448546a7ca3e39e, []int{0}
}
func (m *HostFreqScalingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostFreqScalingConfig.Unmarshal(m, b)
}
func (m *HostFreqScalingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostFreqScalingConfig.Marshal(b, m, deterministic)
}
func (dst *HostFreqScalingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostFreqScalingConfig.Merge(dst, src)
}
func (m *HostFreqScalingConfig) XXX_Size() int {
	return xxx_messageInfo_HostFreqScalingConfig.Size(m)
}
func (m *HostFreqScalingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HostFreqScalingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HostFreqScalingConfig proto.InternalMessageInfo

func (m *HostFreqScalingConfig) GetFreqScalPolicies() map[string]*HostFreqScalingPolicy {
	if m != nil {
		return m.FreqScalPolicies
	}
	return nil
}

func (m *HostFreqScalingConfig) GetFreqSensorUrl() string {
	if m != nil {
		return m.FreqSensorUrl
	}
	return ""
}

func (m *HostFreqScalingConfig) GetBoottimeFreqPolicy() string {
	if m != nil {
		return m.BoottimeFreqPolicy
	}
	return ""
}

func (m *HostFreqScalingConfig) GetHightoLowFreqPolicy() string {
	if m != nil {
		return m.HightoLowFreqPolicy
	}
	return ""
}

type HostFreqScalingPolicy struct {
	ScalingGovernor      string   `protobuf:"bytes,1,opt,name=scaling_governor,json=scalingGovernor,proto3" json:"scaling_governor,omitempty"`
	ScalingMinFreq       string   `protobuf:"bytes,2,opt,name=scaling_min_freq,json=scalingMinFreq,proto3" json:"scaling_min_freq,omitempty"`
	ScalingMaxFreq       string   `protobuf:"bytes,3,opt,name=scaling_max_freq,json=scalingMaxFreq,proto3" json:"scaling_max_freq,omitempty"`
	NodeArch             string   `protobuf:"bytes,4,opt,name=node_arch,json=nodeArch,proto3" json:"node_arch,omitempty"`
	NodePlatform         string   `protobuf:"bytes,5,opt,name=node_platform,json=nodePlatform,proto3" json:"node_platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostFreqScalingPolicy) Reset()         { *m = HostFreqScalingPolicy{} }
func (m *HostFreqScalingPolicy) String() string { return proto.CompactTextString(m) }
func (*HostFreqScalingPolicy) ProtoMessage()    {}
func (*HostFreqScalingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_hostfrequencyscaling_b448546a7ca3e39e, []int{1}
}
func (m *HostFreqScalingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostFreqScalingPolicy.Unmarshal(m, b)
}
func (m *HostFreqScalingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostFreqScalingPolicy.Marshal(b, m, deterministic)
}
func (dst *HostFreqScalingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostFreqScalingPolicy.Merge(dst, src)
}
func (m *HostFreqScalingPolicy) XXX_Size() int {
	return xxx_messageInfo_HostFreqScalingPolicy.Size(m)
}
func (m *HostFreqScalingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_HostFreqScalingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_HostFreqScalingPolicy proto.InternalMessageInfo

func (m *HostFreqScalingPolicy) GetScalingGovernor() string {
	if m != nil {
		return m.ScalingGovernor
	}
	return ""
}

func (m *HostFreqScalingPolicy) GetScalingMinFreq() string {
	if m != nil {
		return m.ScalingMinFreq
	}
	return ""
}

func (m *HostFreqScalingPolicy) GetScalingMaxFreq() string {
	if m != nil {
		return m.ScalingMaxFreq
	}
	return ""
}

func (m *HostFreqScalingPolicy) GetNodeArch() string {
	if m != nil {
		return m.NodeArch
	}
	return ""
}

func (m *HostFreqScalingPolicy) GetNodePlatform() string {
	if m != nil {
		return m.NodePlatform
	}
	return ""
}

func init() {
	proto.RegisterType((*HostFreqScalingConfig)(nil), "proto.HostFreqScalingConfig")
	proto.RegisterMapType((map[string]*HostFreqScalingPolicy)(nil), "proto.HostFreqScalingConfig.FreqScalPoliciesEntry")
	proto.RegisterType((*HostFreqScalingPolicy)(nil), "proto.HostFreqScalingPolicy")
}

func init() {
	proto.RegisterFile("hostfrequencyscaling.proto", fileDescriptor_hostfrequencyscaling_b448546a7ca3e39e)
}

var fileDescriptor_hostfrequencyscaling_b448546a7ca3e39e = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0x53, 0xfa, 0xf0, 0xe4, 0x61, 0x79, 0x10, 0xb2, 0x8a, 0x69, 0xd0, 0x03, 0xc1, 0xc4,
	0xe0, 0x85, 0x98, 0x72, 0x31, 0xde, 0x8c, 0xf1, 0xe5, 0xa0, 0x09, 0xc1, 0x78, 0xae, 0xa5, 0x6e,
	0xdb, 0x8d, 0xcb, 0x0e, 0x6c, 0x97, 0x97, 0x7e, 0x53, 0xbf, 0x83, 0x5f, 0xc2, 0xec, 0xec, 0x12,
	0x82, 0x72, 0x6a, 0xf3, 0x9f, 0xdf, 0x6f, 0x66, 0x3a, 0x25, 0x9d, 0x1c, 0x0a, 0x9d, 0x2a, 0x36,
	0x5f, 0x30, 0x99, 0x94, 0x45, 0x12, 0x0b, 0x2e, 0xb3, 0xc1, 0x4c, 0x81, 0x06, 0x5a, 0xc5, 0x47,
	0xef, 0xab, 0x42, 0xda, 0x8f, 0x50, 0xe8, 0x7b, 0xc5, 0xe6, 0x2f, 0x16, 0xb8, 0x05, 0x99, 0xf2,
	0x8c, 0xbe, 0x11, 0x6a, 0xd4, 0xc8, 0x68, 0xd1, 0x0c, 0x04, 0x4f, 0x38, 0x2b, 0x02, 0xaf, 0xeb,
	0xf7, 0xeb, 0x61, 0x68, 0x9b, 0x0c, 0xf6, 0x9a, 0x83, 0x4d, 0x32, 0x72, 0xd2, 0x9d, 0xd4, 0xaa,
	0x1c, 0xb7, 0xd2, 0x1f, 0x31, 0x3d, 0x27, 0x4d, 0x3b, 0x81, 0xc9, 0x02, 0x54, 0xb4, 0x50, 0x22,
	0xa8, 0x74, 0xbd, 0x7e, 0x6d, 0xdc, 0x40, 0x14, 0xd3, 0x57, 0x25, 0xe8, 0x25, 0x39, 0x9a, 0x00,
	0x68, 0xcd, 0xa7, 0x2c, 0x42, 0x01, 0xb7, 0x29, 0x03, 0x1f, 0x61, 0xba, 0xa9, 0x99, 0xb1, 0xd8,
	0xbb, 0xa4, 0x43, 0x72, 0x9c, 0xf3, 0x2c, 0xd7, 0x10, 0x09, 0x58, 0xed, 0x38, 0x7f, 0xd0, 0x39,
	0xb4, 0xd5, 0x27, 0x58, 0x6d, 0xa5, 0x4e, 0x4c, 0xda, 0x7b, 0x37, 0xa7, 0x2d, 0xe2, 0x7f, 0xb0,
	0x32, 0xf0, 0x50, 0x35, 0xaf, 0x34, 0x24, 0xd5, 0x65, 0x2c, 0x16, 0x0c, 0xf7, 0xad, 0x87, 0xa7,
	0xfb, 0xcf, 0x61, 0xfb, 0x8e, 0x2d, 0x7a, 0x5d, 0xb9, 0xf2, 0x7a, 0x9f, 0xde, 0xaf, 0x6b, 0xbb,
	0x8d, 0x2f, 0x48, 0xcb, 0xfd, 0x9f, 0x28, 0x83, 0x25, 0x53, 0x12, 0x94, 0x1b, 0xd8, 0x74, 0xf9,
	0x83, 0x8b, 0x69, 0x7f, 0x8b, 0x4e, 0xb9, 0xc4, 0xaf, 0x73, 0x77, 0x3b, 0x70, 0xf9, 0x33, 0x97,
	0x66, 0xc2, 0x0e, 0x19, 0xaf, 0x2d, 0xe9, 0xef, 0x92, 0xf1, 0x1a, 0xc9, 0x13, 0x52, 0x93, 0xf0,
	0xce, 0xa2, 0x58, 0x25, 0xb9, 0xbb, 0xd1, 0x3f, 0x13, 0xdc, 0xa8, 0x24, 0xa7, 0x67, 0xa4, 0x81,
	0xc5, 0x99, 0x88, 0x75, 0x0a, 0x6a, 0x1a, 0x54, 0x11, 0xf8, 0x6f, 0xc2, 0x91, 0xcb, 0x26, 0x7f,
	0xf1, 0x04, 0xc3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xdb, 0xe4, 0xcf, 0x74, 0x02, 0x00,
	0x00,
}
