// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rfdiscovery.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RFDiscoveryConfig struct {
	Servers              map[string]*RFDiscoveryServer   `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IpUrl                string                          `protobuf:"bytes,2,opt,name=ip_url,json=ipUrl,proto3" json:"ip_url,omitempty"`
	AggUrl               string                          `protobuf:"bytes,3,opt,name=agg_url,json=aggUrl,proto3" json:"agg_url,omitempty"`
	PollingInterval      string                          `protobuf:"bytes,4,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	RfThermalThresholds  map[string]*RFThermalThresholds `protobuf:"bytes,5,rep,name=rf_thermal_thresholds,json=rfThermalThresholds,proto3" json:"rf_thermal_thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *RFDiscoveryConfig) Reset()         { *m = RFDiscoveryConfig{} }
func (m *RFDiscoveryConfig) String() string { return proto.CompactTextString(m) }
func (*RFDiscoveryConfig) ProtoMessage()    {}
func (*RFDiscoveryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_rfdiscovery_0103bb0f17dc8d08, []int{0}
}
func (m *RFDiscoveryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RFDiscoveryConfig.Unmarshal(m, b)
}
func (m *RFDiscoveryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RFDiscoveryConfig.Marshal(b, m, deterministic)
}
func (dst *RFDiscoveryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RFDiscoveryConfig.Merge(dst, src)
}
func (m *RFDiscoveryConfig) XXX_Size() int {
	return xxx_messageInfo_RFDiscoveryConfig.Size(m)
}
func (m *RFDiscoveryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RFDiscoveryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RFDiscoveryConfig proto.InternalMessageInfo

func (m *RFDiscoveryConfig) GetServers() map[string]*RFDiscoveryServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *RFDiscoveryConfig) GetIpUrl() string {
	if m != nil {
		return m.IpUrl
	}
	return ""
}

func (m *RFDiscoveryConfig) GetAggUrl() string {
	if m != nil {
		return m.AggUrl
	}
	return ""
}

func (m *RFDiscoveryConfig) GetPollingInterval() string {
	if m != nil {
		return m.PollingInterval
	}
	return ""
}

func (m *RFDiscoveryConfig) GetRfThermalThresholds() map[string]*RFThermalThresholds {
	if m != nil {
		return m.RfThermalThresholds
	}
	return nil
}

type RFDiscoveryServer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ReqTimeout           int32    `protobuf:"varint,4,opt,name=req_timeout,json=reqTimeout,proto3" json:"req_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RFDiscoveryServer) Reset()         { *m = RFDiscoveryServer{} }
func (m *RFDiscoveryServer) String() string { return proto.CompactTextString(m) }
func (*RFDiscoveryServer) ProtoMessage()    {}
func (*RFDiscoveryServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_rfdiscovery_0103bb0f17dc8d08, []int{1}
}
func (m *RFDiscoveryServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RFDiscoveryServer.Unmarshal(m, b)
}
func (m *RFDiscoveryServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RFDiscoveryServer.Marshal(b, m, deterministic)
}
func (dst *RFDiscoveryServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RFDiscoveryServer.Merge(dst, src)
}
func (m *RFDiscoveryServer) XXX_Size() int {
	return xxx_messageInfo_RFDiscoveryServer.Size(m)
}
func (m *RFDiscoveryServer) XXX_DiscardUnknown() {
	xxx_messageInfo_RFDiscoveryServer.DiscardUnknown(m)
}

var xxx_messageInfo_RFDiscoveryServer proto.InternalMessageInfo

func (m *RFDiscoveryServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RFDiscoveryServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RFDiscoveryServer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RFDiscoveryServer) GetReqTimeout() int32 {
	if m != nil {
		return m.ReqTimeout
	}
	return 0
}

type RFThermalThresholds struct {
	LowerNormal          int32    `protobuf:"varint,1,opt,name=lower_normal,json=lowerNormal,proto3" json:"lower_normal,omitempty"`
	UpperNormal          int32    `protobuf:"varint,2,opt,name=upper_normal,json=upperNormal,proto3" json:"upper_normal,omitempty"`
	LowerHigh            int32    `protobuf:"varint,3,opt,name=lower_high,json=lowerHigh,proto3" json:"lower_high,omitempty"`
	UpperHigh            int32    `protobuf:"varint,4,opt,name=upper_high,json=upperHigh,proto3" json:"upper_high,omitempty"`
	LowerCritical        int32    `protobuf:"varint,5,opt,name=lower_critical,json=lowerCritical,proto3" json:"lower_critical,omitempty"`
	UpperCritical        int32    `protobuf:"varint,6,opt,name=upper_critical,json=upperCritical,proto3" json:"upper_critical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RFThermalThresholds) Reset()         { *m = RFThermalThresholds{} }
func (m *RFThermalThresholds) String() string { return proto.CompactTextString(m) }
func (*RFThermalThresholds) ProtoMessage()    {}
func (*RFThermalThresholds) Descriptor() ([]byte, []int) {
	return fileDescriptor_rfdiscovery_0103bb0f17dc8d08, []int{2}
}
func (m *RFThermalThresholds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RFThermalThresholds.Unmarshal(m, b)
}
func (m *RFThermalThresholds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RFThermalThresholds.Marshal(b, m, deterministic)
}
func (dst *RFThermalThresholds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RFThermalThresholds.Merge(dst, src)
}
func (m *RFThermalThresholds) XXX_Size() int {
	return xxx_messageInfo_RFThermalThresholds.Size(m)
}
func (m *RFThermalThresholds) XXX_DiscardUnknown() {
	xxx_messageInfo_RFThermalThresholds.DiscardUnknown(m)
}

var xxx_messageInfo_RFThermalThresholds proto.InternalMessageInfo

func (m *RFThermalThresholds) GetLowerNormal() int32 {
	if m != nil {
		return m.LowerNormal
	}
	return 0
}

func (m *RFThermalThresholds) GetUpperNormal() int32 {
	if m != nil {
		return m.UpperNormal
	}
	return 0
}

func (m *RFThermalThresholds) GetLowerHigh() int32 {
	if m != nil {
		return m.LowerHigh
	}
	return 0
}

func (m *RFThermalThresholds) GetUpperHigh() int32 {
	if m != nil {
		return m.UpperHigh
	}
	return 0
}

func (m *RFThermalThresholds) GetLowerCritical() int32 {
	if m != nil {
		return m.LowerCritical
	}
	return 0
}

func (m *RFThermalThresholds) GetUpperCritical() int32 {
	if m != nil {
		return m.UpperCritical
	}
	return 0
}

func init() {
	proto.RegisterType((*RFDiscoveryConfig)(nil), "proto.RFDiscoveryConfig")
	proto.RegisterMapType((map[string]*RFThermalThresholds)(nil), "proto.RFDiscoveryConfig.RfThermalThresholdsEntry")
	proto.RegisterMapType((map[string]*RFDiscoveryServer)(nil), "proto.RFDiscoveryConfig.ServersEntry")
	proto.RegisterType((*RFDiscoveryServer)(nil), "proto.RFDiscoveryServer")
	proto.RegisterType((*RFThermalThresholds)(nil), "proto.RFThermalThresholds")
}

func init() { proto.RegisterFile("rfdiscovery.proto", fileDescriptor_rfdiscovery_0103bb0f17dc8d08) }

var fileDescriptor_rfdiscovery_0103bb0f17dc8d08 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xa7, 0x9b, 0x2a, 0x93, 0x52, 0xda, 0xad, 0x2a, 0x56, 0x91, 0x10, 0x25, 0x52,
	0xa5, 0x72, 0x89, 0xa0, 0x5c, 0x10, 0x17, 0x0e, 0x05, 0x04, 0x17, 0x0e, 0x4b, 0x38, 0x5b, 0x6e,
	0xba, 0x5e, 0xaf, 0xd8, 0x78, 0xb7, 0xe3, 0xb5, 0x51, 0xde, 0x92, 0xb7, 0xe0, 0x35, 0x90, 0x67,
	0x9d, 0xb4, 0x95, 0xdb, 0x93, 0x47, 0xff, 0xff, 0xcd, 0xcc, 0xbf, 0x1e, 0x38, 0xc6, 0xe2, 0xc6,
	0xd4, 0x2b, 0xd7, 0x2a, 0xdc, 0x2c, 0x3c, 0xba, 0xe0, 0x38, 0xa3, 0xcf, 0xfc, 0xef, 0x08, 0x8e,
	0xe5, 0xd7, 0xcf, 0x5b, 0xf3, 0xca, 0x55, 0x85, 0xd1, 0xfc, 0x13, 0xec, 0xd7, 0x0a, 0x5b, 0x85,
	0xb5, 0x48, 0xce, 0x46, 0x17, 0xd3, 0xcb, 0xf3, 0xd8, 0xb5, 0x18, 0xa0, 0x8b, 0x9f, 0x91, 0xfb,
	0x52, 0x05, 0xdc, 0xc8, 0x6d, 0x17, 0x3f, 0x85, 0xb1, 0xf1, 0x59, 0x83, 0x56, 0xa4, 0x67, 0xc9,
	0xc5, 0x44, 0x32, 0xe3, 0x7f, 0xa1, 0xe5, 0x2f, 0x60, 0x3f, 0xd7, 0x9a, 0xf4, 0x11, 0xe9, 0xe3,
	0x5c, 0xeb, 0xce, 0x78, 0x03, 0x47, 0xde, 0x59, 0x6b, 0x2a, 0x9d, 0x99, 0x2a, 0x28, 0x6c, 0x73,
	0x2b, 0xf6, 0x88, 0x78, 0xde, 0xeb, 0xdf, 0x7b, 0x99, 0x2b, 0x38, 0xc5, 0x22, 0x0b, 0xa5, 0xc2,
	0x75, 0x6e, 0xb3, 0x50, 0xa2, 0xaa, 0x4b, 0x67, 0x6f, 0x6a, 0xc1, 0x28, 0xe9, 0xbb, 0x27, 0x93,
	0xca, 0x62, 0x19, 0x9b, 0x96, 0xbb, 0x9e, 0x98, 0xfa, 0x04, 0x87, 0xce, 0x6c, 0x09, 0x07, 0xf7,
	0x9f, 0xc6, 0x8f, 0x60, 0xf4, 0x5b, 0x6d, 0x44, 0x42, 0xa1, 0xba, 0x92, 0x2f, 0x80, 0xb5, 0xb9,
	0x6d, 0x14, 0x3d, 0x71, 0x7a, 0x29, 0x86, 0x8b, 0xe3, 0x00, 0x19, 0xb1, 0x8f, 0xe9, 0x87, 0x64,
	0x76, 0x0d, 0xe2, 0xa9, 0x18, 0x8f, 0x6c, 0x78, 0xfb, 0x70, 0xc3, 0x6c, 0xb7, 0x61, 0x30, 0xe1,
	0xde, 0x8e, 0xb9, 0x7d, 0x70, 0xd1, 0x98, 0x81, 0x73, 0xd8, 0xab, 0xf2, 0xb5, 0xea, 0xa7, 0x53,
	0xcd, 0x0f, 0x21, 0x35, 0xbe, 0x3f, 0x50, 0x6a, 0x7c, 0xc7, 0x78, 0x87, 0x81, 0x4e, 0xc3, 0x24,
	0xd5, 0xfc, 0x15, 0x4c, 0x51, 0xdd, 0x66, 0xc1, 0xac, 0x95, 0x6b, 0x02, 0xdd, 0x84, 0x49, 0x40,
	0x75, 0xbb, 0x8c, 0xca, 0xfc, 0x5f, 0x02, 0x27, 0x8f, 0x04, 0xe2, 0xaf, 0xe1, 0xc0, 0xba, 0x3f,
	0x0a, 0xb3, 0xca, 0x75, 0x0e, 0x2d, 0x66, 0x72, 0x4a, 0xda, 0x0f, 0x92, 0x3a, 0xa4, 0xf1, 0xfe,
	0x0e, 0x49, 0x23, 0x42, 0x5a, 0x8f, 0xbc, 0x04, 0x88, 0x53, 0x4a, 0xa3, 0xcb, 0x3e, 0xd8, 0x84,
	0x94, 0x6f, 0x46, 0x97, 0x9d, 0x1d, 0x27, 0x90, 0x1d, 0xc3, 0x4d, 0x48, 0x21, 0xfb, 0x1c, 0x0e,
	0x63, 0xf7, 0x0a, 0x4d, 0x30, 0xab, 0xdc, 0x0a, 0x46, 0xc8, 0x33, 0x52, 0xaf, 0x7a, 0xb1, 0xc3,
	0xe2, 0x94, 0x1d, 0x36, 0x8e, 0x18, 0xa9, 0x5b, 0xec, 0x7a, 0x4c, 0x7f, 0xff, 0xfd, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x36, 0xbb, 0xea, 0x4d, 0x03, 0x00, 0x00,
}
