// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RFDiscovery.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RFDiscoveryConfig struct {
	Servers              map[string]*RFAggregatorServer `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PollingInterval      string                         `protobuf:"bytes,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	NameUrl              string                         `protobuf:"bytes,3,opt,name=name_url,json=nameUrl,proto3" json:"name_url,omitempty"`
	ServerUrl            string                         `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	UuidUrl              string                         `protobuf:"bytes,5,opt,name=uuid_url,json=uuidUrl,proto3" json:"uuid_url,omitempty"`
	IpUrl                string                         `protobuf:"bytes,6,opt,name=ip_url,json=ipUrl,proto3" json:"ip_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RFDiscoveryConfig) Reset()         { *m = RFDiscoveryConfig{} }
func (m *RFDiscoveryConfig) String() string { return proto.CompactTextString(m) }
func (*RFDiscoveryConfig) ProtoMessage()    {}
func (*RFDiscoveryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_RFDiscovery_ed5d26dc17e8b4d2, []int{0}
}
func (m *RFDiscoveryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RFDiscoveryConfig.Unmarshal(m, b)
}
func (m *RFDiscoveryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RFDiscoveryConfig.Marshal(b, m, deterministic)
}
func (dst *RFDiscoveryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RFDiscoveryConfig.Merge(dst, src)
}
func (m *RFDiscoveryConfig) XXX_Size() int {
	return xxx_messageInfo_RFDiscoveryConfig.Size(m)
}
func (m *RFDiscoveryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RFDiscoveryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RFDiscoveryConfig proto.InternalMessageInfo

func (m *RFDiscoveryConfig) GetServers() map[string]*RFAggregatorServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *RFDiscoveryConfig) GetPollingInterval() string {
	if m != nil {
		return m.PollingInterval
	}
	return ""
}

func (m *RFDiscoveryConfig) GetNameUrl() string {
	if m != nil {
		return m.NameUrl
	}
	return ""
}

func (m *RFDiscoveryConfig) GetServerUrl() string {
	if m != nil {
		return m.ServerUrl
	}
	return ""
}

func (m *RFDiscoveryConfig) GetUuidUrl() string {
	if m != nil {
		return m.UuidUrl
	}
	return ""
}

func (m *RFDiscoveryConfig) GetIpUrl() string {
	if m != nil {
		return m.IpUrl
	}
	return ""
}

type RFAggregatorServer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RFAggregatorServer) Reset()         { *m = RFAggregatorServer{} }
func (m *RFAggregatorServer) String() string { return proto.CompactTextString(m) }
func (*RFAggregatorServer) ProtoMessage()    {}
func (*RFAggregatorServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_RFDiscovery_ed5d26dc17e8b4d2, []int{1}
}
func (m *RFAggregatorServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RFAggregatorServer.Unmarshal(m, b)
}
func (m *RFAggregatorServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RFAggregatorServer.Marshal(b, m, deterministic)
}
func (dst *RFAggregatorServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RFAggregatorServer.Merge(dst, src)
}
func (m *RFAggregatorServer) XXX_Size() int {
	return xxx_messageInfo_RFAggregatorServer.Size(m)
}
func (m *RFAggregatorServer) XXX_DiscardUnknown() {
	xxx_messageInfo_RFAggregatorServer.DiscardUnknown(m)
}

var xxx_messageInfo_RFAggregatorServer proto.InternalMessageInfo

func (m *RFAggregatorServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RFAggregatorServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RFAggregatorServer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*RFDiscoveryConfig)(nil), "proto.RFDiscoveryConfig")
	proto.RegisterMapType((map[string]*RFAggregatorServer)(nil), "proto.RFDiscoveryConfig.ServersEntry")
	proto.RegisterType((*RFAggregatorServer)(nil), "proto.RFAggregatorServer")
}

func init() { proto.RegisterFile("RFDiscovery.proto", fileDescriptor_RFDiscovery_ed5d26dc17e8b4d2) }

var fileDescriptor_RFDiscovery_ed5d26dc17e8b4d2 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5f, 0x4b, 0xc3, 0x40,
	0x0c, 0xc0, 0x69, 0xb7, 0x76, 0x5b, 0x26, 0x3a, 0x03, 0x42, 0x2b, 0x08, 0x63, 0x20, 0xcc, 0x97,
	0x0a, 0xf3, 0x45, 0x7c, 0x11, 0xf1, 0x0f, 0x08, 0x3e, 0x55, 0xfa, 0x3c, 0xaa, 0x9e, 0xe5, 0xf0,
	0xec, 0x1d, 0xe9, 0xb5, 0xd0, 0xaf, 0xe7, 0x27, 0x93, 0xcb, 0x55, 0x51, 0xf6, 0xd4, 0x24, 0xbf,
	0x5f, 0xd2, 0xe4, 0xe0, 0x30, 0x7f, 0xb8, 0x93, 0xcd, 0xab, 0xee, 0x04, 0xf5, 0x99, 0x21, 0x6d,
	0x35, 0x46, 0xfc, 0x59, 0x7d, 0x85, 0xff, 0xe0, 0xad, 0xae, 0xdf, 0x65, 0x85, 0xd7, 0x30, 0x69,
	0x04, 0x75, 0x82, 0x9a, 0x24, 0x58, 0x8e, 0xd6, 0xf3, 0xcd, 0xa9, 0xef, 0xca, 0x76, 0xd4, 0xec,
	0xd9, 0x7b, 0xf7, 0xb5, 0xa5, 0x3e, 0xff, 0xe9, 0xc2, 0x33, 0x58, 0x18, 0xad, 0x94, 0xac, 0xab,
	0xad, 0xac, 0xad, 0xa0, 0xae, 0x54, 0x49, 0xb8, 0x0c, 0xd6, 0xb3, 0xfc, 0x60, 0xa8, 0x3f, 0x0e,
	0x65, 0x4c, 0x61, 0x5a, 0x97, 0x9f, 0x62, 0xdb, 0x92, 0x4a, 0x46, 0xac, 0x4c, 0x5c, 0x5e, 0x90,
	0xc2, 0x13, 0x00, 0x3f, 0x90, 0xe1, 0x98, 0xe1, 0xcc, 0x57, 0x1c, 0x4e, 0x61, 0xda, 0xb6, 0xf2,
	0x8d, 0x61, 0xe4, 0x3b, 0x5d, 0xee, 0xd0, 0x11, 0xc4, 0xd2, 0x30, 0x88, 0x19, 0x44, 0xd2, 0x14,
	0xa4, 0x8e, 0x0b, 0xd8, 0xfb, 0xbb, 0x2f, 0x2e, 0x60, 0xf4, 0x21, 0xfa, 0x24, 0x60, 0xc7, 0x85,
	0x78, 0x0e, 0x51, 0x57, 0xaa, 0x56, 0xf0, 0xb6, 0xf3, 0x4d, 0xfa, 0x7b, 0xf7, 0x4d, 0x55, 0x91,
	0xa8, 0x4a, 0xab, 0xc9, 0x4f, 0xc8, 0xbd, 0x77, 0x15, 0x5e, 0x06, 0xab, 0x27, 0xc0, 0x5d, 0x01,
	0x11, 0xc6, 0xee, 0x90, 0x61, 0x3a, 0xc7, 0xb8, 0x0f, 0xa1, 0x34, 0xc3, 0x4b, 0x84, 0xd2, 0x38,
	0xc7, 0x68, 0xb2, 0x7c, 0x78, 0x94, 0x73, 0xfc, 0x12, 0xf3, 0x2f, 0x2f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x88, 0x08, 0x67, 0x2c, 0xb5, 0x01, 0x00, 0x00,
}
